### ISSUE TITLE
Optimize the web reader and/or improve webkit support

### ISSUE THREAD

**Issue by DisableGraphics** [hkalexling/Mango#102]
I have a crappy tablet where I read my comics. The problem is, the loading times for the comics are painfully slow when using chrome or firefox.

I have a faster browser (on the tablet), but it's based on webkit and can't launch the web reader, tapping on it won't show anything, instead of showing the reader menu where you can select to read (I tested it also with an iPad, in safari, and doesn't work either).

It would be pretty good if this amazing application worked well on that tablet.

Tablet specs:
    - 512MB RAM
    - 1Ghz dual core

**Comment by hkalexling** [comment]
Hi, thanks for reaching out!

> the loading times for the comics are painfully slow when using chrome or firefox.

- Are you experiencing the slowness on the web reader (`/reader/...`) or the title page of the comic (`/book/...`)? 
- Which version of Mango are you using?
- Where are you hosting Mango? Is it on a remote server or a local machine?

> I have a faster browser (on the tablet), but it's based on webkit and can't launch the web reader

The web reader works without any issue in Safari on my iPhone and iPad. Are you running an outdated iOS?

**Comment by DisableGraphics** [comment]
I'm experiencing the slowness on the web reader.
I'm using the 0.12.0 version
I'm hosting it on my PC, connected to the same wifi.

I forgot to mention the iPad has iOS 9.0. I think the browser of the tablet (not iPad) is probably based on an older version of webkit.

**Comment by hkalexling** [comment]
I see. Unfortunately it's impossible for me to support old safaris. I don't have a device to install iOS9 to test it :( 

> I think the browser of the tablet (not iPad) is probably based on an older version of webkit.

May I know what browser it is and its version? I will be happy to install and test it if possible.

> I'm experiencing the slowness on the web reader.

The web reader has been rewritten since v0.12.0 (though the UI looks the same), which might be responsible for the slowness you are experiencing. Have you used an older version (say v0.11.0) of Mango before? Was it any better?

**Comment by hkalexling** [comment]
You can try [v0.12.3](https://github.com/hkalexling/Mango/releases/tag/v0.12.3) which has improved support for legacy browsers. I've tested it in Safari 9.1 using [BrowserStack](https://live.browserstack.com/dashboard) and the reader works without any issues.

**Comment by DisableGraphics** [comment]
Thank you very much for your effort. The web reader now works perfectly on my tablet. I will close the issue since the problem was solved.
