### ISSUE TITLE
[Bug Report] "Next Entry", HTTP 404 due to page 0

### ISSUE THREAD

**Issue by DJScias** [hkalexling/Mango#104]
**Describe the bug**
When going to the next entry, it loads the next page on page 0 and it stops working.

**To Reproduce**
1. Continue reading or just begin reading
2. Go to bottom and check "Next Entry"
3. Get greeted with `HTTP 404: Mango cannot find the page`
![image](https://user-images.githubusercontent.com/439655/93495258-3870db00-f90e-11ea-83b3-986d3b65673f.png)

**Expected behavior**
The next entry shown to me, page 1.

**Environment (please complete the following information):**
 - OS: Synology DS918+, DSM 6.2.3-25426 
 - Browser: N/A
 - Mango Version: v0.12.1

**Docker (if you are running Mango in a Docker container)**
Don't know how to get all the correct info, but this is how the container is made:
```
sudo docker create \
  --name=mango \
  -e PUID=1024 \
  -e PGID=100 \
  -p 9000:9000/tcp \
  -v /volume1/docker/Mango/config:/root/.config/mango \
  -v /volume4/Plex4/Mango:/root/mango \
  --restart always \
	hkalexling/mango:v0.12.1
```

**Additional context**
I can fix the url by changing the 0 to 1 like:
`/reader/0b4ae83371f742dbaacec7310e1849ab/45211d73b2dd4d3ca79bf89384bbdff2/0`
to
`/reader/0b4ae83371f742dbaacec7310e1849ab/45211d73b2dd4d3ca79bf89384bbdff2/1`

**Comment by hkalexling** [comment]
Wow, it's a pretty serious bug. Fixed in [v0.12.2](https://github.com/hkalexling/Mango/releases/tag/v0.12.2) now. Thanks for reporting!
