### ISSUE TITLE
[Feature Request] Disable Login

### ISSUE THREAD

**Issue by ducky710** [hkalexling/Mango#107]
Just coming back to project, it's been a few months since i've checked in and I wondered if it's possible to disable auth somehow? I use Authelia so a way to turn off the built in login would be great.

**Comment by hkalexling** [comment]
Hi, thanks for reaching out! At this moment there's no way to disable it, but I see that it can be useful so I will be happy to add an option to disable it. I am turning this into a feature request.

**Comment by ducky710** [comment]
Oh okay great! Thanks, looking forward to it :)

**Comment by hkalexling** [comment]
Hey sorry for the long delay! In [v0.18.0](https://github.com/hkalexling/Mango/releases/tag/v0.18.0) you can now disable the login and specify a default user.

**Comment by ducky710** [comment]
Yoooo nice! Thanks man!
