### ISSUE TITLE
[Feature Request] Add support for nested folders in library

### ISSUE THREAD

**Issue by inthebrilliantblue** [hkalexling/Mango#11]
I tend to organize manga based on artist / writer and other tags, so my folder structure looks like this:

Library
-Artist
    --Ken Akamatsu
        ---Love Hina
        ---A.I. Love You
    --Shimoku Kio
        ---Genshiken
        ---Genshiken Nidaime
-Mags
    --NewType
        ---[Range of folders with timestamps for monthly releases]
-Other
    --Sort
        ---[Random assortment of stuff, including pdfs]
-etc.

So I would like Mango to be able to scan the subfolders of its library, and present it as subfolders / containers / whatever you wanna call it. This is actually an issue I have with Komga, as it can read subfolders, but treats the last containing folder as the "Series" for its contents. This isnt bad, but with no metadata support it makes it hard to use for me as it combines all these last folder names into one list that is displayed to the end user, so you would see stuff like this:
Love Hina
A.I. Love You
Genshiken
Genshiken Nidaime
[NewType Timestamp]
[NewType Timestamp]
[Other Mag Timestamp]
[Other Other Mag Timestamp]
[Random Book]
[Random Book]
[Random Book]

Not at all how I would want these ebooks / manga presented to me.

**Comment by hkalexling** [comment]
I agree! It would be a nice feature to have. I will try to include this in the next release.

**Comment by hkalexling** [comment]
This feature is added in [v0.2.1](https://github.com/hkalexling/Mango/releases/tag/v0.2.1). Thanks for the request!
