### ISSUE TITLE
[Feature Request] Dark Theme by default

### ISSUE THREAD

**Issue by koala784** [hkalexling/Mango#111]
Hi, is there a way to set the dark theme by default ?

Something like :

`theme: dark`

in the config.yml file ?

Thanks for your project ! :)

**Comment by hkalexling** [comment]
Hi there, sorry for the delay - I have been terribly busy in the past few days.

There's no way to do this at this moment, and I am turning this into a feature request. Do you have a use-case for this feature?

**Comment by koala784** [comment]
I'l using a lot of services that I share with some friends (Plex, Nextcloud,...) with Organizr, and all the services are dark by default. When switching between services, it can be flashy if you don't know how to change the theme (yes I know it's easy). It's not annoying (and it's not important), but could be a cool option for the future :)

**Comment by hkalexling** [comment]
Hi, sorry for the long delay! In [v0.17.1](https://github.com/hkalexling/Mango/releases/tag/v0.17.1), Mango would use the system theme setting by default. So if you have dark mode enabled, Mango would show the dark theme. Thanks for the request!

**Comment by koala784** [comment]
Thanks !!
