### ISSUE TITLE
[Bug Report] Archive error: Couldn't find directory end signature in the last 65KB

### ISSUE THREAD

**Issue by koala784** [hkalexling/Mango#112]
**Describe the bug**
Can't add some .CBZ files, this error is visible on the website and in the log : 

```
/root/mango/library/Archives/Shokugeki no Soma/Tome 31.cbz
Archive error: Couldn't find directory end signature in the last 65KB
```

![Logs](https://user-images.githubusercontent.com/24566850/94377739-24a25180-0124-11eb-833c-776df495f4ca.png)

![Mango Error 65Kb](https://user-images.githubusercontent.com/24566850/94377740-253ae800-0124-11eb-8682-ab70051ee30e.png)

**To Reproduce**
Going on the website and trying to read the recently added files
Starting a scan and viewing the errors on the log

**Expected behavior**
Mango should scan correctly this files, and they should be readable then on the website.

**Environment (please complete the following information):**
 - OS : UnRAID (Docker)
 - Browser : Firefox (not relevant here I think)
 - Mango Version : v0.12.3

**Docker (if you are running Mango in a Docker container)**
- I don't use Docker compose, but an UnRAID template

**Additional context**

I have added 5 .CBZ files on a folder (vol. 31 to 36 of Shokugeki no Soma). The others .CBZ files are OK.
I've made this .CBZ with the defaults settings of 7zip.

Similar to #7 and #90 
But I don't use Mango for Downloading, only for serving the files.

- I can read the .CBZ correctly with another reader (MComix 1.2.1).

![MComix](https://user-images.githubusercontent.com/24566850/94377841-ccb81a80-0124-11eb-9a10-3648cd227a5b.png)

- The 7zip control don't find any error.

![7zip](https://user-images.githubusercontent.com/24566850/94377737-2409bb00-0124-11eb-8860-0935f1036a39.png)

Sorry if there's someting missing^^

**Comment by hkalexling** [comment]
Could you send me a cbz file in question so I can inspect it? You can reach me at email@hkalexling.com. Thanks!

**Comment by koala784** [comment]
Email sended ;)

**Comment by hkalexling** [comment]
Hey, sorry for the LOOONG delay! I took a look and your archives are 7zip and not regular zip files. Manga archives compressed with 7zip usually have the `.cb7` extension, and Mango expects all files with the `.cbz` extension to be valid zip files. See https://en.wikipedia.org/wiki/Comic_book_archive.

Unfortunately 7zip is not yet supported. How many such files do you have? If you want to read them in Mango, you might want to write a script to bulk convert them to valid cbz files.
