### ISSUE TITLE
[Bug Report] Permission Denied | From ???? | (after a power loss)

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#115]
**Describe the bug**
After a power failure, as soon as you try to start mango (WSL1) this error appears:
![image](https://user-images.githubusercontent.com/17975351/94943030-6857db00-04d7-11eb-8692-b9e2e7b822c8.png)

**To Reproduce**
1. Mango running on WSL with Windows Server 2019
2. Turn off the power to the server
3. Start mango

**Environment (please complete the following information):**
 - OS: Windows Server 2019 with WSL1 Ubuntu 20
 - Mango Version 0.12.3

**Additional context**
Already checked if hdd where WSL resides and Ubuntu are damaged.

**Comment by hkalexling** [comment]
Hi, please verify that the config file exists and the current user has the permission to read it.

**Comment by zFerry98** [comment]
> Hi, please verify that the config file exists and the current user has the permission to read it.

I chmod the .config/mango folder but it didn't work.
The file exists.

**Comment by zFerry98** [comment]
Solved by uninstalling ubuntu and re-installing it.
Since I use the alternative Paths it was enough for me to re-configure the config and the rest was automatically restored.

Solved by uninstalling ubuntu and reinstalling it.
Since I use alternative PATHs, it was enough for me to re-configure the config and the rest was automatically restored.

Only thing I noticed, the first start does a scan, right? If you open the mango web page it tells you that there are 0 entries in the db and you see the server as if you have no manga in the library. Let's say that the first time I got really bad. Then just wait for the scan to finish and everything goes back to normal.

thanks anyway.

**Comment by hkalexling** [comment]
Yes the initial scan takes a bit longer and it might be the reason why you are seeing an empty library. 

For future reference, if it happens again you can run `ls -l /path/to/config.yml` and paste the output here.

**Comment by zFerry98** [comment]
![image](https://user-images.githubusercontent.com/17975351/95011741-38254f00-0633-11eb-8e88-ca47dc8b9679.png)
GG 🤬😪😥🤷‍♂️😂

**Comment by zFerry98** [comment]
Ok, nice wsl bug. If the power fails it does not save the permissions in the FS. I put the config.yml in rwxX and now it works. I'd say it's a WSL bug and not Mango. Thanks anyway
