### ISSUE TITLE
[Bug Report] Loading slowly with large entries

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#116]
**Is your feature request related to a problem? Please describe.**
The latest version is really good except the manga loading speed. When the manga entries have more over 100 books (or chapters) it will load the 100 books cover at once, and it causes the load speed very slowly. 

**Describe the solution you'd like**
Load static number of books in one page or lazyload them

**Comment by hkalexling** [comment]
Mango uses [UIKit](https://getuikit.com/docs/) as its UI framework and it does lazy load images. Only images visible in the viewport will be loaded. Can you verify this in the network tab in the Chrome dev tool?

**Comment by WROIATE** [comment]
With Chrome dev tool I found lazy load correctly. But when I open a entries with 200 books, It will load slowly

![Snipaste_2020-10-20_10-55-04](https://user-images.githubusercontent.com/44677306/96534642-ba17a800-12c2-11eb-8a75-66e88f6c2be5.png)

And when I open an entires has less books, it will load fast with almost same content size 

7 books
![7 books](https://user-images.githubusercontent.com/44677306/96533973-76706e80-12c1-11eb-820a-603e1dc7b7d6.png)

13 books
![13 books](https://user-images.githubusercontent.com/44677306/96534803-0d89f600-12c3-11eb-8654-fc8cc6ab3493.png)

So at first, I thought mango not use lazyload by my feeling, Its my fault.

**Comment by WROIATE** [comment]
I change this issue title to bug report

**Comment by hkalexling** [comment]
Some optimizations have been introduced in [v0.15.0](https://github.com/hkalexling/Mango/releases/tag/v0.15.0). For example, Mango will now generate low-resolution thumbnails, and only visible titles will be trucated. Can you try and see if it helps?

I know pagination would be a more effective fix, but that would require a search API from the backend so I am still considering it.

**Comment by WROIATE** [comment]
@hkalexling 
With version 0.15.0, the loading speed improved.
But the cost time did not match expectations
![Snipaste_2020-10-26_11-51-17](https://user-images.githubusercontent.com/44677306/97132362-a74d1980-1781-11eb-94c0-3848afb84be1.png)

To comparing with the version 0.14.1, I can load a 13 books entries in 2 seconds and 200 books entries in 11 seconds with both about 26MB content size ( because of lazy load it will load the same number of images and almost same content size at first ). The latest version used thumbnails decreased the content size to 5MB, also cost about 6 seconds.

So I guess the problem maybe not the image size but the backstage load meta data speed slowly?

**Comment by hkalexling** [comment]
The title page load time has been improved in [v0.17.1](https://github.com/hkalexling/Mango/releases/tag/v0.17.1). I tested it with a title containing 1000 entries, and in v0.17.0 the load time was 12.53 seconds, and in the latest version, it's 6.03 seconds. Can you try and see if it helps?

**Comment by WROIATE** [comment]
> The title page load time has been improved in [v0.17.1](https://github.com/hkalexling/Mango/releases/tag/v0.17.1). I tested it with a title containing 1000 entries, and in v0.17.0 the load time was 12.53 seconds, and in the latest version, it's 6.03 seconds. Can you try and see if it helps?

Bravo! This version is well!

**Comment by WROIATE** [comment]
@hkalexling
I found Mango will not show the cover with library by default now. Is this normally?

**Comment by hkalexling** [comment]
Do the entries in the title have covers?

**Comment by WROIATE** [comment]
> Do the entries in the title have covers?

Yes.
![Snipaste_2020-12-28_22-03-03](https://user-images.githubusercontent.com/44677306/103219377-8313e180-4958-11eb-8e64-97ae85d4ce6e.png)

**Comment by hkalexling** [comment]
Ah I see. So Mango has two concepts called titles and entries. A title can contain a list of entries and optionally a list of sub-titles, and an entry is just a single archive (in zip/cbz or rar/cbr). In your case, it looks like the "test" title has no entries in it (though the sub-titles do), and in this case, it just shows the Mango icon as its title cover. This has always been the logic behind the covers. If you can read Crystal/Ruby, the method that gets returns the cover URL can be found here.

**Comment by WROIATE** [comment]
> Ah I see. So Mango has two concepts called titles and entries. A title can contain a list of entries and optionally a list of sub-titles, and an entry is just a single archive (in zip/cbz or rar/cbr). In your case, it looks like the "test" title has no entries in it (though the sub-titles do), and in this case, it just shows the Mango icon as its title cover. This has always been the logic behind the covers. If you can read Crystal/Ruby, the method that returns the cover URL can be found here
> 
> https://github.com/hkalexling/Mango/blob/f7b8e2d852bd90b2130437c62f8f001451f557fc/src/library/title.cr#L161-L174

I got it. Thanks : )
