### ISSUE TITLE
[Bug Report] Build error on raspberry pi

### ISSUE THREAD

**Issue by ChristofferGreen** [hkalexling/Mango#119]
/opt/bin$ sudo git clone https://github.com/hkalexling/Mango.git
/opt/bin$ cd Mango/
/opt/bin/Mango:master$ sudo cp env.example .env
/opt/bin/Mango:master$ sudo vim .env (only changed the port number here)
/opt/bin/Mango:master$ sudo docker-compose up
Creating mango ... error

ERROR: for mango  Cannot create container for service mango: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for mango  Cannot create container for service mango: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.

------------------

According to: https://stackoverflow.com/questions/59904878/docker-compose-volume-name-is-too-short-names-should-be-at-least-two-alphanume
If the following lines in docker-compose.yml are changed:
      - ${MAIN_DIRECTORY_PATH}:/root/mango
      - ${CONFIG_DIRECTORY_PATH}:/root/.config/mango

to:

      - ${MAIN_DIRECTORY_PATH}/:/root/mango
      - ${CONFIG_DIRECTORY_PATH}/:/root/.config/mango

It works (and it did for me)

----------------

Some docker info:
/opt/bin/Mango:master$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 20
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.75GiB
 Name: raspberrypi
 ID: WLCL:5KTE:V4IQ:2JE7:NHIP:4ADS:3F5A:KVY6:BPGJ:IC5N:6ZMO:BTDA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support

**Comment by hkalexling** [comment]
Hi there, you are supposed to set the `MAIN_DIRECTORY_PATH` and `CONFIG_DIRECTORY_PATH` variables in the `.env` file. They are resolved to empty strings as you didn't specify the values, and so Docker complains that they are too short.
