### ISSUE TITLE
[Feature Request] alphanumeric sort on page

### ISSUE THREAD

**Issue by Leeingnyo** [hkalexling/Mango#12]
Hi, I'm beginning to use the Mango!
It's so good to support the docker thank you!

Here I have a issue about page sorting.
I read #9  also, however that issue was a kind of chapter sorting.
In my zip file, the images are named as

```
1.jpg
2.jpg
3.jpg
...
10.jpg
11.jpg
...
```

When I open the comics via Mango, the page are sorted as

```
1.jpg
10.jpg
11.jpg
...
2.jpg
...
3.jpg
...
```

There are maybe several methods for resolving this, I found this post[Stack Exchange: how-should-sorting-work-when-numeric-is-mixed-with-alpha-numeric](https://ux.stackexchange.com/questions/95431/how-should-sorting-work-when-numeric-is-mixed-with-alpha-numeric).
Could you check this one?

**Comment by hkalexling** [comment]
Hi, thanks for the feature request!

Most [cbz](https://en.wikipedia.org/wiki/Comic_book_archive) files add leading zeros to the filenames (e.g., `001.jpg` to `100.jpg`) to make sure the images are displayed in the correct order. It looks like your zip/cbz file didn't follow this convention.

I think what we can do is:

1. Check whether the image filenames contain only numerical values.
2. If so, check whether the filenames have leading zeros.
3. If there's no leading zero, we parse the filenames and sort them by the numerical values.
4. In other cases, we sort the images by filenames as strings. 

This should be pretty easy to implement. I will work on this soon, and in the meantime feel free to let me know if you have any further suggestions on this issue.

**Comment by Leeingnyo** [comment]
Oh yes. unfortunately my zip file doesn't have leading zeros...

I just made a code in the Crystal, which is implemented about method of above link
Here, https://repl.it/@Leeingnyo/ValidVigilantLinuxpc
Since I'm not used to the Crystal Language, this code should have some refactoring process.

I checked your comment lately... I would follow your opinion

**Comment by hkalexling** [comment]
Your code looks good. If you want, feel free to submit a PR to the development branch [v0.2.0](https://github.com/hkalexling/Mango/tree/v0.2.0). Don't worry; I would make some further modifications if there's any performance issue.

**Comment by Leeingnyo** [comment]
Okay! I'll make PR. I'm glad to contribute!

**Comment by hkalexling** [comment]
This is added in version [v0.2.0](https://github.com/hkalexling/Mango/releases/tag/v0.2.0). Thanks again for your contribution :D
