### ISSUE TITLE
[Bug Report] [ARM64] Crashing during downloads 

### ISSUE THREAD

**Issue by dudeamax99** [hkalexling/Mango#120]
**Describe the bug**
Mango Server crashing while downloading Manga.

**To Reproduce**
1. Add any Manga to the download queue in Mango
2. Wait for crash (20 minutes should be enough to trigger.)

**Expected behavior**
App doesn't crash; continues downloading.

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.0.4 LTS, aarch64
 - Mango Version: Commit bf68e32

**Docker (if you are running Mango in a Docker container)**
```
# Port that exposes the HTTP frontend
PORT=8080

# Path to the mango main directory
# This directory holds the database and the library files
MAIN_DIRECTORY_PATH=/home/ubuntu/mango

# Path to the mango config directory
# This directory holds the mango configuration path
CONFIG_DIRECTORY_PATH=/home/ubuntu/mango
```
Using [arm64v8 Dockerfile](https://github.com/hkalexling/Mango/blob/master/Dockerfile.arm64v8) 

**Additional context**
Crash message 
```mango    | Failed to raise an exception: -1016404928
mango    | [0xaaaab9f84868] ???
mango    | [0xaaaab9e0cc20] __crystal_raise +36
mango    | [0xaaaab9e45a70] ???
mango    | [0xaaaab9e4579c] ???
mango    | [0xaaaab9e5ecf8] ???
mango    | [0xffff889576e0] ???
mango exited with code 64```

**Comment by hkalexling** [comment]
Thanks for the bug report! I did reproduce the issue but it happens randomly so I am still trying to figure out the culprit :(

**Comment by hkalexling** [comment]
Hi, I am returning to this issue and I found that I can no longer reproduce it with the latest version of Mango ([v0.17.1](https://github.com/hkalexling/Mango/releases/tag/v0.17.1)). 

I had both v0.17.1 and v0.15.0 running side by side on an ARM64 machine and added hundreds of chapters to each download queue. The old version crashed after ~40mins, but the latest version worked fine even when downloading for a few hours straight. The latest version uses an updated version of Crystal and that might have fixed this issue.

Do you think you can give v0.17.1 a try and see if it helps? Thanks!

**Comment by dudeamax99** [comment]
Can confirm no more crashes or errors. Thanks!

**Comment by hkalexling** [comment]
Great! Thanks a lot for checking!
