### ISSUE TITLE
[Bug Report] Continuous Progress does not update and save unless mode is changed

### ISSUE THREAD

**Issue by DJScias** [hkalexling/Mango#121]
**Describe the bug**
Scroll through a manhua to the bottom without choosing "Next Entry", it'll not update itself after the first page UNLESS you switch "Mode" from "Continuous" to "Paged" and back to "Continuous".

The last entry in a manhua/manga is extra annoying because it does not have the "Next Entry" button (which marks said entry as read) but only an "Exit Reader" button which doesn't put the entry at 100%.

Due to the nature of the "Next Entry" button marking 100% it sort of masks the issue unless you pay attention.

***Note:* This testing is done through a manhua called "Solo Leveling", so a continuous strip and not a paged manga.**

**To Reproduce**

**Random entry**
1. Open a manga and choose a random entry that is unread
2. Read through the whole entry but do not go to "Next Entry", just go out of the manga
3. Notice the entry isn't marked as 100%

**Last Entry**
1. Open a manga and choose the last entry
2. Read through the last entry and choose "Exit Reader"
3. Notice the last entry isn't marked as 100%

This entirely bugs out the last entry considering there's no "Next Entry" button that marks it as read.

![image](https://user-images.githubusercontent.com/439655/97768711-63f9fe80-1b25-11eb-973c-f6b7060974fd.png)

**Expected behavior**
The entry marks itself as 100% read without having to do a Mode switch trick.

**Environment (please complete the following information):**
 - OS: Synology DS918+, DSM 6.2.3-25426 
 - Browser: N/A
 - Mango Version: v0.15.0

**Docker (if you are running Mango in a Docker container)**
```
sudo docker create \
  --name=mango \
  -e PUID=1024 \
  -e PGID=100 \
  -p 9000:9000/tcp \
  -v /volume1/docker/Mango/config:/root/.config/mango \
  -v /volume4/Plex4/Mango:/root/mango \
  --restart always \
	hkalexling/mango:v0.15.0
```

**Additional context**
In the past I used a Tampermonkey script that sometimes had trouble with Mango but I've stopped using that so I can confirm it's unrelated to this.

I did notice that once again (as I once had issues with in a previous issue) the `/1` part does not update in this manhua strip.
![image](https://user-images.githubusercontent.com/439655/97768753-b0453e80-1b25-11eb-9012-a446d0e500d8.png)

**However!:** If I change the "mode" from Continuous to Paged and then BACK to Continuous the url does update to `/2` etc...
![image](https://user-images.githubusercontent.com/439655/97768769-cf43d080-1b25-11eb-8800-3674c41f62d4.png)

Maybe it's doing something wrong on first load in regards to "Continuous"? No clue.
But when I open an entry and I don't do the mode change it does not update the url for me.

I hope the above info is enough to reproduce. If there's more questions, please don't hesitate in asking them. It's a minor issue as I just "mark as read" the last entry but it'd be easier if it actually worked of course. :P

**Comment by hkalexling** [comment]
It should now be fixed in [v0.15.1](https://github.com/hkalexling/Mango/releases/tag/v0.15.1). Thanks for the bug report!
