### ISSUE TITLE
[Bug Report] Setting URL base gives "to many redirects" error

### ISSUE THREAD

**Issue by JunkKnight** [hkalexling/Mango#122]
**Describe the bug**
When a URL base is set via the config.yml file the web interface is no longer accessible ether by local IP or through reverse proxy.

**To Reproduce**
1. Set URL base
2. Try to access web UI ether at local IP or proxy-ed address

**Expected behavior**
I would expect the URL base to be added to the end of the address and load the page.

**Environment (please complete the following information):**
 - OS: Unraid 6.8.3
 - Browser: Tested in Firefox and Edge
 - Mango Version: 0.15.1

**Docker (if you are running Mango in a Docker container)**
- Docker configured by Unraid's built in UI. Only Port and Manga library location set.

- Docker version 19.03.5
- Network in bridge mode

**Additional context**

![Screenshot 2020-11-06 120734](https://user-images.githubusercontent.com/8772612/98410075-37684a00-2031-11eb-9691-f701916d42f8.png)
Edge error
![Screenshot 2020-11-06 120628](https://user-images.githubusercontent.com/8772612/98410088-40591b80-2031-11eb-8d8a-a9c305878807.png)
Firefox error

Without the URL base set Mango works fine and is accessible over the local network at the local IP:port. When the URL base is set I found that deleting the base part from the URL (so going to address:port/login instead of address:port/base/login) will load a plain text login page without any formatting, but trying to login just redirects back to the non-working login page shown above.

**Comment by hkalexling** [comment]
To use the base URL you should configure your revere proxy properly. Please take a look at https://github.com/hkalexling/Mango/wiki/Additional-Configurations#base-url.

**Comment by JunkKnight** [comment]
Just to confirm then, does this mean defining a URL base means Mango can no longer be accessed directly by it's local IP (typing in 192.168.x.x:port)? I ask because I get the same error whether I access directly like that or through the reverse proxy, in this case Nginx using a basic proxy setup through Nginx Proxy Manger. Based on the documentation Mango shouldn't need any special configuration in Nginx so I used the same configuration I use for a number of other services for it so I assumed it should work.

**Comment by alethiophile** [comment]
I have this same problem. I have configured my reverse proxy according to the guide, and it's still failing.

It would be good to get some clarity as to exactly what configuration of the reverse proxy is necessary to make this work.

**Comment by hkalexling** [comment]
@alethiophile You opened #260 so I assumed you got Nginx working?

To clarify the points raised above, if you want to use a custom base URL, you will have to set up a reverse proxy and access the app through it. With a custom base URL accessing IP:port won't work.

**Comment by alethiophile** [comment]
Yes, I got nginx working (and got caddy past this issue, at least).

It seems the relevant consideration here is that the reverse proxy must send all requests to mango rooted at /, i.e. it must turn a request for /urlroot/login into just /login. In nginx, this is controlled by the presence or absence of a / in the location specifier; in caddy, it requires using the `handle_path` directive rather than `handle`.

**Comment by ocgineer** [comment]
I have the same issue getting the 'too many redirects' with nginx ([SWAG](https://github.com/linuxserver/docker-swag) on Unraid) and this is the only app so far that I have issues with setting a sub-folder config.

I followed the wiki's default configuration and I tried the Swag default sub-folder configurations but all got the same issue.

I tried;
- location /manga/  as described in the wiki of Mango.
- location ^~ /manga/
- location /manga { return 301 $scheme://$host/manga/; } in combination with location ^~ /manga/
- Used the wiki proxy config
- Used SWAG default proxy config

The last  one is what I use for many other apps and is mostly the default config for other apps in SWAG. So am I still doing something wrong as following the wiki (base url) didn't seem to work neither the 'default' swag configs.

**Comment by hkalexling** [comment]
@ocgineer How are you accessing Mango? Do you use `ip:port` or `domain.tld:port`? Only the latter will go through your reverse proxy.

The Nginx config in the wiki works on raw Nginx, but I've never used Unraid or Swag and maybe they handle proxy requests differently.

**Comment by ocgineer** [comment]
I access it via `https://books.domain.tld/manga` or tried also `https://domain.tld/manga`.

SWAG is an docker container that has nginx, reverse proxy, and certification build in, running Mango also in a docker on the same custom docker network as the reverse proxy, I have no issues accessing Mango itself without base url and directly on a subdomain.

**Comment by hkalexling** [comment]
@ocgineer I am not entirely sure but the https redirect shouldn't be an issue. Let me give Swag a try later and see if I can reproduce the error.
