### ISSUE TITLE
[Bug? / Feature Request] Failed to generate thumbnail for entry

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#123]
As the title suggests, I don't understand if it's a bug or if the jpegs are really damaged. The other error is "Index out of bounds".

![image](https://user-images.githubusercontent.com/17975351/98465798-c7da9200-21cb-11eb-96d4-cfea4af9ce66.png)

Suspicious file links (uploaded to mega): https://mega.nz/folder/Al8FHQaC#jbayRkMYTUy1Z3SMLJURRg

The feature request is to put the full path on the "failed to generate thumbnail for entry" error. 
As you can see from the screen, I do not understand which series "volume 03 / Chapter 22 -" refers to, since the base folder or full path is not added.

**Comment by hkalexling** [comment]
I think both of them have corrupted pages. See the screenshot below:

![Screenshot 2020-11-08 at 9 59 53 PM](https://user-images.githubusercontent.com/7845831/98466977-cf228f80-220d-11eb-9df8-ff138517f3c8.png)

You can verify this by unzipping both files and check their first pages. The first page in "Capitolo 436 -  436.zip" has zero bytes, and the first page in "Ch. 565 - God Like You.cbz" has only 16 bytes.

Yes, I agree we should print out the full path for these entries. I will update it in the next version. Thanks for the suggestion!

BTW, I found multiple corrupted pages in "Ch. 565 - God Like You.cbz". Did you download it using the MangaDex downloaer in Mango? If so there might be a bug in the downloader 🤔

**Comment by zFerry98** [comment]
> Did you download it using the MangaDex downloader in Mango? 

No, they were downloaded with Emule (these 2 specific).
The others I can't find, however, have "AGC" in the name. Those chapters are .zips downloaded directly from the site of the group that translates them (downloaded with IDM). If I knew exactly which series they belong to, I could check if I was the one who downloaded badly or if they are really corrupt. Now I try to see all the series that have that name and control.

**Comment by hkalexling** [comment]
In [v0.16.0](https://github.com/hkalexling/Mango/releases/tag/v0.16.0), Mango would log the full path of the entries.
