### ISSUE TITLE
[Bug Report] Restarting Docker on Unraid deletes users and admin password info

### ISSUE THREAD

**Issue by tylernguyen** [hkalexling/Mango#125]
**Describe the bug**
Stop/Starting or Restarting Docker container will result in all user info loss, admin password is reset and any other users are deleted.

**To Reproduce**
Go to Docker tab in Unraid, Stop/Start container or Restart container.

**Expected behavior**
User information should be retained post restarts.

**Environment (please complete the following information):**
- Unraid 6.8.3

**Docker (if you are running Mango in a Docker container)**
- default docker container in Unraid

**Additional context**
Log below with user `tyler` created then deleted post reboot.
```
[91m[ERROR] [0m2020/11/29 13:44:11 | Error when verifying user tyler: no results
```

**Comment by hkalexling** [comment]
Hi, I am not familiar with Unraid, but Docker itself is just stateless, and you are supposed to map two volumes for persistent storage when creating the container. Please see these lines: https://github.com/hkalexling/Mango/blob/master/docker-compose.yml#L14-L15

**Comment by BradleyDS2** [comment]
To anyone else who encounters this issue, the problem is with the Unraid app template for Mango.
I recommend following the changes noted [here](https://forums.unraid.net/topic/87798-support-selfhostersnets-template-repository/?do=findComment&comment=1088485).
