### ISSUE TITLE
[Bug Report]Cannot build the docker container on a Raspberry 4B

### ISSUE THREAD

**Issue by rainbowbreeze** [hkalexling/Mango#126]
I tried to build the docker container for my raspi4b, and the process stopped with this error
```
Step 4/9 : RUN apk add --no-cache yarn yaml sqlite-static libarchive-dev libarchive-static acl-static expat-static zstd-static lz4-static bzip2-static libjpeg-turbo-dev libpng-dev tiff-dev
 ---> Running in 44f1f5a18ef6
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'mango' failed to build : The command '/bin/sh -c apk add --no-cache yarn yaml sqlite-static libarchive-dev libarchive-static acl-static expat-static zstd-static lz4-static bzip2-static libjpeg-turbo-dev libpng-dev tiff-dev' returned a non-zero code: 1
```

**To Reproduce**
On a raspberry pi, with Raspbian Buster installed and the environment configured to run docker and docker-compose

git clone https://github.com/hkalexling/Mango.git mango
cd mango
cp env.example .env
vi .env
docker-compose up

** Env **
uname -a
```
Raspian version: Linux xxxxxxxx 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
```

cat /etc/os-release 
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by hkalexling** [comment]
Hi, the default Dockerfile can only be used on amd64/x86-64 hosts. Your RPi has an ARM CPU and you should use the corresponding [Dockerfile for ARM32](https://github.com/hkalexling/Mango/blob/master/Dockerfile.arm32v7). You might want to take a look at the [wiki](https://github.com/hkalexling/Mango/wiki/Platform-Support#arm32v7arm64v8).

**Comment by rainbowbreeze** [comment]
Thanks! I thought the switch was automatic.

Suggestion: Worthwhile adding a comment to the ARM image to check on the wiki for the right way to build the container
