### ISSUE TITLE
[Question][Docker] how do you setup user right

### ISSUE THREAD

**Issue by julien-vu** [hkalexling/Mango#129]
Hi,
The container starts, set up admin and pwd correctly,
Mount a volume for config and data,
First every file created by the container are owned by root, how can I use current user ? tried to set my user (1000:1000) in the docker-compose, no success so far

~~Secondly when I move a zip to library, the scan cant read it~~

**Solved the scan issue : need to have folder under library**

**Comment by hkalexling** [comment]
Hi, thanks for reaching out!

> First every file created by the container are owned by root, how can I use current user ?

This is the default behavior of docker. To specify a user just use the `user` option as you mentioned.

> tried to set my user (1000:1000) in the docker-compose, no success so far

Did you use a fresh volume? If not some files in the volume would be created and owned by root and therefore not accessible by your current user.

**Comment by julien-vu** [comment]
Thanks ! your question solved my issue

For everyone : create the Library folder before the mount or else the docker container will create the folder

My current tree created beforehand

/<path to data>/mango_data/Library
