### ISSUE TITLE
[Question] docker-compose up: exec format error?

### ISSUE THREAD

**Issue by zachstultz** [hkalexling/Mango#133]
My experience with docker has usually been using the docker create command, I'm not super familiar with docker-compose, so this is probably user error, but this is what I get when I run docker-compose up.

`sudo docker-compose up
Recreating mango ... done
Attaching to mango
mango    | standard_init_linux.go:219: exec user process caused: exec format error
mango exited with code 1`

This is my docker-compose.yml

> version: '3'

>services:
  mango:
    image: hkalexling/mango
    container_name: mango
    expose:
      - 9070
    ports:
      - 9070:9070
    volumes:
      - /home/pi/docker/mango:/home/pi/docker/mango
      - /home/pi/docker/mango/config:/home/pi/docker/mango/config

**Comment by zachstultz** [comment]
Realized I'm trying to run it on my raspberry pi, which is ARM, and Mango only supports amd64/x86-64.

**Comment by hkalexling** [comment]
Mango does support ARM. Please check the [wiki](https://github.com/hkalexling/Mango/wiki/Platform-Support).

**Comment by hkalexling** [comment]
Also for the `ports` field, you probably want `- 9070:9000`

**Comment by zachstultz** [comment]
> 
> 
> Mango does support ARM. Please check the [wiki](https://github.com/hkalexling/Mango/wiki/Platform-Support).

Ohhh, I had no idea. So I just went ahead and followed all the steps and compiled it with port 9070. It starts up, but I get this error.

```

Mango - Manga Server and Web Reader. Version 0.17.1,

[ERROR]   2021/01/10 03:44:46 | Error when checking tables in DB: database is locked,
Unhandled exception: database is locked (SQLite3::Exception),
  from __w/Mango/Mango/lib/sqlite3/src/sqlite3/connection.cr:91:11 in 'close',
  from __w/Mango/Mango/lib/db/src/db/pool.cr:50:21 in 'close',
  from __w/Mango/Mango/lib/db/src/db.cr:123:7 in '->',
  from __w/Mango/Mango/src/queue.cr:112:3 in 'default',
  from __w/Mango/Mango/src/queue.cr:11:7 in 'default',
  from __w/Mango/Mango/src/mango.cr:47:3 in '->',
  from usr/share/crystal/src/mutex.cr:47:9 in '__crystal_main',
  from usr/share/crystal/src/crystal/main.cr:39:9 in 'main',
  from __libc_start_main
```

**Comment by hkalexling** [comment]
I guess your DB files are in a network mounted drive? In that case, you would need to edit the config file and point them to local paths. Please see https://github.com/hkalexling/Mango/issues/138#issuecomment-756037848.

**Comment by zachstultz** [comment]
> 
> 
> I guess your DB files are in a network mounted drive? In that case, you would need to edit the config file and point them to local paths. Please see [#138 (comment)](https://github.com/hkalexling/Mango/issues/138#issuecomment-756037848).

Yeah they're all on a NAS Drive. I redirected the db file configs, and changed a couple docker config settings and it's all working now, thanks for all the help!
