### ISSUE TITLE
[Bug Report] Progress Not Being Updated

### ISSUE THREAD

**Issue by ChessDragon136** [hkalexling/Mango#142]
**Describe the bug**
Progress is not being updated correctly upon leaving a volume on any given page when using continuous mode. 
Inspection of the info.json file shows that I have read up to page 1 (Which was the page I started the volume at) 
Issue only started recently, suspect it is related to v0.18.0 release in the last few days.
**Edit: Confirmed - Rollback to 0.17.1 resolved this issue**

**To Reproduce**
Set a volume to unread
Start reading (ensure continuous mode) and randomly select any page to stop at
Exit the reader in the normal way
Update shows low percentage, equal to page 1

**Expected behavior**
The info.json page number to reflect correctly 

**Environment (please complete the following information):**
Docker implementation on UnRaid.
Mango v0.18.0

**Additional Info**
At first I thought this to be a permissions issue, but marking a volume as fully read or unread works correctly.

**Comment by hkalexling** [comment]
Thanks for the bug report! The bug is now fixed in [v0.18.1](https://github.com/hkalexling/Mango/releases/tag/v0.18.1).

**Comment by ChessDragon136** [comment]
Thanks for the swift resolution - Fix confirmed working.
