### ISSUE TITLE
[Question] Changing Library Path (Docker)

### ISSUE THREAD

**Issue by Dino-V** [hkalexling/Mango#145]
Hey!

I'm running Mango on Docker. So far, everything's been working fine, but the library_path set is `/root/mango/library`.

I'd like to change it to a folder in my Documents folder (C:/Users/XXX/Documents/Mango Library). However, I'm not sure how to do this. I've tried the following, all to no avail:

- '/mnt/c/Users/XXX/Documents/Mango Library'
- '/mnt/host/c/Users/XXX/Documents/Mango Library'
- '/root/Documents/Mango Library'

Any idea on how to get this to work? Thanks!

**Comment by hkalexling** [comment]
Hi, thanks for reaching out!

> I've tried the following, all to no avail

Could you be more specific? It's always easier for me to diagnose the issue if you could list the steps you did. E.g., Did you update the config file? Did you correctly map the volume to Docker?

**Comment by Dino-V** [comment]
Oops sorry, I meant to say that I've tried all of the following in the library_path variable of "config.yml":
- '/mnt/c/Users/XXX/Documents/Mango Library'
- '/mnt/host/c/Users/XXX/Documents/Mango Library'
- '/root/Documents/Mango Library'

Mango reads it properly, but it says that the directories don't exist. It then tries to create the directory, and after I restart Mango the message goes away (presumably because it's made that directory somewhere... though I'm not sure where). Still, it doesn't point to the intended one because it says "Scanned 0 titles."

I'm not sure if I've correctly mapped the volume to Docker. I didn't do any Docker configurations besides the initial installation/default configurations. My wsl.conf file is this:
`[automount]
root =/mnt/host
crossDistro = true
options = "metadata"`

If I open wsl I can successfully run `cd "/mnt/host/c/Users/XXX/Documents/Mango Library"`

**Comment by hkalexling** [comment]
It looks like you didn't map the volumes to Docker. The Docker container itself is an isolated environment, and you need to map some folders on your host machine to the container so Mango can read from them. Have you followed the [Docker installation guide](https://github.com/hkalexling/Mango#docker)?

**Comment by hkalexling** [comment]
If you are still struggling to configure Docker, you can try to use the pre-built binary instead. You can simply download it from the latest release and run it from your WSL.

**Comment by Dino-V** [comment]
Got it to work! I just edited the volumes part of the `docker-compose.yml` file.

Quick question: I've been looking everywhere but I can't seem to figure out how (and if it's recommended) to move the .docker, mango, and .config folders (basically all the Docker-related folders that are currently in C:/Users/XXX/) to my Documents folder instead of the default location (C:/Users/XXX/). Do you by any chance know how to do this (currently using Docker Desktop, if that makes a difference).

**Comment by hkalexling** [comment]
Glad to know that it's working :D 

I don't use Windows at all so I can't really help with that. Perhaps you can ask the folks at [r/docker](https://www.reddit.com/r/docker/)?

**Comment by Dino-V** [comment]
Ah I see. Thanks! :)
