### ISSUE TITLE
[Question] how to set session_secret

### ISSUE THREAD

**Issue by neunenak** [hkalexling/Mango#149]
Hi, I just learned about Mango and am trying it out. I notice that there's a default configuration key called `session_secret` generated with a default value. I don't see anything in the documentation for what, if anything, I should set this to on my system. I assume if it's a secret I shouldn't be using the default value though...

**Comment by hkalexling** [comment]
The session secret is used to sign the session ID of a logged-in user to cookies. You can use anything as long as you keep it safe.
