### ISSUE TITLE
[Question] why I can't scan the file that I upload?

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#15]
I upload the comic file which format is zip, but I can't get it on the server, what's wrong?

![Snipaste_2020-03-17_23-20-06](https://user-images.githubusercontent.com/44677306/76871331-e0491580-68a5-11ea-8346-0bff5a5bdd9d.png)
![Snipaste_2020-03-17_23-19-41](https://user-images.githubusercontent.com/44677306/76871325-de7f5200-68a5-11ea-8e6d-8b77fb22c4d3.png)

**Comment by hkalexling** [comment]
It would be helpful if you could let me know a few things:

1. Are you running Mango in a docker container? If so, did you modify the example docker-compose file?
2. What's inside the zip file? The zip file should contain only images (png or jpeg).

**Comment by hkalexling** [comment]
Ah, I see the problem. You should put the zip file in a nested folder in the library (e.g., `library/manga-name/1.zip`. 

I have updated the README to make it clearer. Please refer to https://github.com/hkalexling/Mango/blob/master/README.md#library-structure

**Comment by WROIATE** [comment]
It works! thanks!

And I tried the docker but found this Dockerfile build a too large image (700MB+), I suggest to replace by this

```
FROM library/alpine

RUN mkdir /root/Mango
WORKDIR /root/Mango

RUN wget https://github.com/hkalexling/Mango/releases/download/v0.2.1/mango && chmod +x ./mango

CMD ["/root/Mango/mango"]
```

Its just 25MB with the same function

**Comment by hkalexling** [comment]
The current docker file builds Mango from source, while the one you provided uses the pre-built binary. I think it's better to stick to the former because some users might not trust the binary I built. 

But it's a good point that I didn't consider. I will investigate and see how we can reduce the image size. Thanks for the suggestion!

**Comment by WROIATE** [comment]
> The current docker file builds Mango from source, while the one you provided uses the pre-built binary. I think it's better to stick to the former because some users might not trust the binary I built.
> 
> But it's a good point that I didn't consider. I will investigate and see how we can reduce the image size. Thanks for the suggestion!

You are right, so I modify the code with the former way, also 25M size
```
FROM crystallang/crystal:0.32.1-alpine
WORKDIR /Mango
COPY . .
COPY package*.json .

RUN apk add --no-cache nodejs yarn sqlite sqlite-doc sqlite-static sqlite-dev sqlite-libs yaml \
        && apk add uglifycss uglify-js --repository http://nl.alpinelinux.org/alpine/edge/testing/ \
        && make static

FROM library/alpine
WORKDIR /root
COPY --from=0 /Mango/mango ./Mango/

CMD ["/root/Mango/mango"]
```

**Comment by hkalexling** [comment]
Looks good! Do you want to submit a PR to the [development branch](https://github.com/hkalexling/Mango/tree/dev)? I will test it a bit and make a new release.
