### ISSUE TITLE
[Feature Request] bulk remove missing items

### ISSUE THREAD

**Issue by Leeingnyo** [hkalexling/Mango#151]
**Is your feature request related to a problem? Please describe.**
I got 300+ missing entries by my mistake (I don't know what happened, sorry).
I can remove them one by one on admin page, but I want a one button solution (230 entries left now!).

**Describe the solution you'd like**
1. add remove-all button on top section of missing item page
2. show the confirm popup after clicking remove-all button
   * yes: remove all, reload the page
   * no: hide the popup

![REMOVE ALL button](https://user-images.githubusercontent.com/6760150/105871607-d30bc400-603c-11eb-9729-2485ece68676.png)
**Figure 1.** 'REMOVE ALL' button

**Describe a small use-case for this feature request**
remove all missing items without clicking hundreds times

**Comment by hkalexling** [comment]
Are you sure you want to remove them all? Can you check that the files exist at the listed relative paths?

I agree we need bulk removal here, but this is from the dev branch so I am still working on it. As a quick workaround, you can always open the DB file (by default it's at `~/mango/mango.db`), and run the following SQL queries

```sql
-- delete unavailable entries
delete from ids where unavailable = 1;

-- delete unavailable titles
delete from titles where unavailable = 1;
```

**Comment by Leeingnyo** [comment]
ah, sorry for bothering you. I didn't mean to push you.

files exist at same position. I dug the DB and found that unavailable items' path are starting with '/' (`/foo/abc.cbz`, `/bar/def.cbz`), available items' path are starting with its directory name (`foo/abc.cbz`, `bar/def.cbz`).
It might be caused since I ran the Mango in various version (? -> newest -> v0.2.0 (by mistake) -> dev).

**Comment by hkalexling** [comment]
No, it's totally fine! That sounds like a bug to me. Let me take a look later and see what the problem is.

For future reference, it might be better to run the `dev` branch on a dedicated machine or in a VM. I have a development server where I run the `dev` branch and have a bunch of testing manga, and a stable server that runs the stable version.

**Comment by hkalexling** [comment]
I just took a look and found the issue. In the DB migration, we are replacing full paths with relative paths with leading slashes. For example, `/home/user/mango/library/book/entry.cbz` will be replaced with `/book/entry.cbz`.

https://github.com/hkalexling/Mango/blob/c1c8cca8779012e4f7262bd3e85ef05f872ec14e/migration/relative_path.8.cr#L3-L14

But when matching library files against DB records, we use relative paths without the leading slashes (e.g., `book/entry.cbz`). 

https://github.com/hkalexling/Mango/blob/c1c8cca8779012e4f7262bd3e85ef05f872ec14e/src/storage.cr#L237

The difference in the format is what caused the issue. I will push a fix to the `dev` branch soon. Thanks for reporting!

**Comment by Leeingnyo** [comment]
It seems to be resolved! I'll close it.

And I had to delete unavailable entries by running SQL in the DB since the Mango failed to migrate the DB automatically by unique constraint on `ids.path`. Someone who experience a same issue should run above SQL queries https://github.com/hkalexling/Mango/issues/151#issuecomment-767987031 on your DB!.
