### ISSUE TITLE
[Bug Report] Theme problem: toggleTheme() doesn't change the setting in ADMIN, and reader page always uses dark background

### ISSUE THREAD

**Issue by somebelly** [hkalexling/Mango#155]
**Describe the bug**
2 issues:
 - when using `toggleTheme()` in `navbar`, the setting in `ADMIN` doesn't change.
 - `reader` page always uses `dark` background even when using `light` theme.

**To Reproduce**
See the video below.

**Expected behavior**
 - when using `toggleTheme()` in `navbar`, the setting in `ADMIN` changes.
 - the background of the `reader` page changes according to the theme.

**Environment (please complete the following information):**
 - OS: KDE neon User Edition 5.20 (Ubuntu 20.04)
 - Browser: Chromium 88.0.4324.96 (Official Build) snap (64-bit)
 - Mango Version: v0.19.1 (binary release)

https://user-images.githubusercontent.com/15066360/106246102-dbffbf80-620d-11eb-9be4-688257007290.mp4

**Comment by hkalexling** [comment]
Hi, thanks for reaching out!

> when using toggleTheme() in navbar, the setting in ADMIN doesn't change.

This is indeed a bug. I will fix it in the next release. Thanks for the bug report!

> reader page always uses dark background even when using light theme.

This is intentional. IMHO the light manga pages don't look good on a white background, so the reader page background is always black, regardless of your theme setting.

**Comment by hkalexling** [comment]
This is now fixed in v0.20.0. Thanks for the bug report!
