### ISSUE TITLE
[Bug Report] absurd cpu usage when using the download manager

### ISSUE THREAD

**Issue by DisableGraphics** [hkalexling/Mango#157]
**Describe the bug**
When using the download manager, my PC's cpu usage skyrockets (>90%)and when closing the its tab, cpu usage returns to normal (0~5%)

**To Reproduce**
1. Open the download manager in a browser tab.
2. Cpu usage will go up to more than 90%

**Expected behavior**
The download manager should not use that much of the cpu (in older versions (i think inferior to 0.13 or something) that didn't happen)

**Environment (please complete the following information):**
 - OS: Manjaro linux
 - Browser: firefox and chrome
 - Mango Version: 0.20.0

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.

**Comment by hkalexling** [comment]
Hi, thanks for the bug report! A few questions:

- How many jobs do you have in your download queue?
- Do you see any errors in the browser log?

**Comment by DisableGraphics** [comment]
Normally, more than 10 jobs is enough to make my cpu go nuts.
There aren't any errors in the browser log as far as I know.

**Comment by DisableGraphics** [comment]
Seems that now the CPU usage is smaller. I will close this issue.
