### ISSUE TITLE
[Feature Request] Automatically Rename/Organize Manga Names/Issues After Download

### ISSUE THREAD

**Issue by dykn** [hkalexling/Mango#16]
Hi,

I was just wondering if it would be possible for you to add a feature where the names of the manga(s) and volumes/chapters/issues would be automatically renamed, perhaps shortly after downloaded or maybe ran on the entire library at a certain interval or schedule.

Maybe something similar to what Sonarr ([https://github.com/Sonarr/Sonarr](url)) or FileBot do for anime, using AniDB or MyAnimeList (if/when their public API opens).

Thanks.

**Comment by hkalexling** [comment]
Hi, thanks for the feature request!

How do you want Mango to rename the files? Personally, I don’t use Sonarr, so it would be great if you could briefly describe the renaming behavior you are looking for.

**Comment by dykn** [comment]
Sorry for the delayed reply.

In Sonarr, it basically allows you to customize the pattern, creation of folders, etc.  Thought I don't think the customization is totally necessary, something like:

**Name Of Manga** / File Name Of Manga - Issue Number.cbz

Would be appropriate.

In Sonarr, the customization settings look like this:

![rename](https://user-images.githubusercontent.com/61395909/77209541-e4a74580-6ad4-11ea-8808-49e9835638bc.png)

Filebot has similar settings/options, forked source here:

https://github.com/barry-allen07/FB-Mod

Thanks.

**Comment by hkalexling** [comment]
Thanks for the clarification. I agree that it would be a useful feature to have.

I don't like the idea of having a long list of options on the web page to customize the naming behavior (as shown in your screenshot above). I think it makes more sense for the users to specify the naming format in the config file. For example, you can write something like 

`- chapter_rename: {title} Vol.{volume} Ch.{chapter}.cbz`

in the config file, and Mango would rename the downloaded files accordingly.

I will try to include this in the next release, but in the meantime, feel free to let me know what you think!

**Comment by hkalexling** [comment]
This feature is now available in [v0.4.0](https://github.com/hkalexling/Mango/releases/tag/v0.4.0). Please check the [Wiki](https://github.com/hkalexling/Mango/wiki/Additional-Configurations#mangadex-rename-rules) for details.
