### ISSUE TITLE
[Question] Auto downloading new chapters?

### ISSUE THREAD

**Issue by FrozenSource** [hkalexling/Mango#167]
Hello!

First let me tell you I love your work guys.
I however have a question, I don't see anywhere that auto downloading of new chapter from for example mangadex is supported?
Is it already a feature, or is it coming?

Sincerely,
FrozenSource

**Comment by hkalexling** [comment]
Hi there! It has been requested in #24 but it's not available yet. I have been working on it but it could take a while. You can subscribe to that issue to get updated.
