### ISSUE TITLE
[Feature Request] Custom sort order

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#182]
**Is your feature request related to a problem? Please describe.**

I happen to find some series that I can't sort them (unless I change the file / folder name). It would be more convenient to be able to add a "sort order" parameter instead of having to rename the physical folders / files and then (logically) change the name.
![image](https://user-images.githubusercontent.com/17975351/112836703-35179280-909b-11eb-9b23-d47237e15a0a.png)

**Describe the solution you'd like**
<details>
 <summary>IMG Ex:</summary>

**Komga:**
![image](https://user-images.githubusercontent.com/17975351/112837244-ef0efe80-909b-11eb-930f-1f104e6e9793.png)
**Komga DB:**
![image](https://user-images.githubusercontent.com/17975351/112838384-4d88ac80-909d-11eb-8431-dbac2e12f796.png)
is my Komga database table.

</details>

**Describe a small use-case for this feature request**
Being able to reorder items without having to change the real name.
Ex:
Series that have a "saga" name that encloses a specific number of volumes (not necessarily continuation volumes:
Saga 1> from volume 1 to 20;
Saga 2> from volume 21 to 40;
or
Saga 1> Volume 1 - 4;
Saga 2> Volume 1 - 25;
In this case, saga 2 is a sequel but not a continuation of the previous volume 4

**Comment by GlassedSilver** [comment]
Like so often, I can only reference iTunes as one of the best metadata managers out there. It certainly doesn't have everything, but I think it's power level is a solid ground base to accomplish a lot of stuff.

iTunes does have alternative sort titles and the like as well, this would be ideal here! Big fan of this suggestion!

Also, a little sidenote: I would suggest the sorting algorithm to not go digit by digit but number by number whereas a number is any chain of digits not interrupted by a dot, comma, semicolon, other special characters or letters. Or a space (` `). :)

The suggested feature would however still be useful whenever the sorting doesn't break due to numbers, but because the order should not be alphabetical when your personal preference is entirely different. (e.g. sort chronologically or by canon timeline, which often isn't necessary the release timeline :) )

**Comment by Leeingnyo** [comment]
Hi!

I would implement this feature :) a plan will be commented soon.

@GlassedSilver Hi, I couldn't understand your comment. for titles in title, it sorts them alphanumerically. we split a name of title to number and non-number (`abc12-3foo456bar` goes `abc`, `12`, `-`, `3`, `foo`, `456`, `bar`) and compare the numbers as a number

**Comment by GlassedSilver** [comment]
> Hi!
> 
> I would implement this feature :) a plan will be commented soon.
> 
> @GlassedSilver Hi, I couldn't understand your comment. for titles in title, it sorts them alphanumerically. we split a name of title to number and non-number (`abc12-3foo456bar` goes `abc`, `12`, `-`, `3`, `foo`, `456`, `bar`) and compare the numbers as a number
> 
> Ah yes. we would use the same algorithm on this feature. don't worry.

The sort title basically acts as an override for sorting as opposed to how the title appears in the UI and meta-data tracking.

E.g.: Say you have Harry Potter movies and the titles include "Harry Potter and the Philosopher's Stone".

Obviously sorting these sorts of titles by the usual alphabetical approach will result in the problem of them being out of order.

What I'd do in iTunes is to - if I don't like renaming the titles to "Harry Potter 1 - and the Philosopher's Stone" (already looks hella icky!) - to leave the regular title field to itself and type "Harry Potter 1" into the sorting title field.

**Comment by Leeingnyo** [comment]
oh sorry I was talking about this

> Also, a little sidenote: I would suggest the sorting algorithm to not go digit by digit but number by number whereas a number is any chain of digits not interrupted by a dot, comma, semicolon, other special characters or letters. Or a space ( ). :)

I might misread something.
Yes, you're right. I would add another name field for a custom sorting

A plan:
the names for a custom sorting info

* would be saved in the info.json temproray. 
* has the key-value structure (`{ "a name of entry file": "a custom name for sorting"  }`).
* has a global scope (it's not user specific info).
* could be edited by admins.

in a title page (a book page), a 'Custom' up and down options would be added.
With custom sort option, entires that have custom name would be appeared firstly. i.e.

```
[sorted entries using custom sort name alphanumerically]
[sorted entries that have no custom sort name using auto / or its name alphanumerically]
```

so does reversed.

hmm.. as I know, there's no sorting option for titles (folders) in title now... we would resolve this first. I don't know if this is a design decision.
also there isn't a UI for editing title info either.

**Comment by hkalexling** [comment]
@Leeingnyo You rock! I still need to find the time to review the other PR from you :-)

> hmm.. as I know, there's no sorting option for titles (folders) in title now... we would resolve this first. I don't know if this is a design decision.

Yes, currently the sub-titles are not sorted. My rationale was that the number of sub-titles is usually small (at least in my use-case), so sorting them is not important (but certainly won't hurt).

> in a title page (a book page), a 'Custom' up and down options would be added.

I guess we can add this to the default "Auto" sort option? When sorting, if an entry has a custom sort title, we would use that to sort, and otherwise, we would fall back to its actual title. If you don't add sort titles to the entries their order will stay the same, so this won't break the user expectation.

**Comment by Leeingnyo** [comment]
@hkalexling It would be good that sorting titles is supported, for comfortable mind :) let me try to do it together. currently title sorting options in library page are "Auto", "Data Modified" and "Progress" and entry sorting options has "Name" and "Data Added" more. Adding both options for titles would be easy.

> I guess we can add this to the default "Auto" sort option? When sorting, if an entry has a custom sort title, we would use that to sort, and otherwise, we would fall back to its actual title. If you don't add sort titles to the entries their order will stay the same, so this won't break the user expectation.

Sounds good! Then, custom sort title would be used in "Auto" and "Title" options, right? Is it needed that a mark shows that the title has a custom sort name in an item card UI? or should we show a custom sort name in somewhere?

**Comment by Leeingnyo** [comment]
It's another question, should we use display_name for sorting in "Auto" and "Title"?

**Comment by hkalexling** [comment]
@Leeingnyo Thanks for taking on this :+1: 

> custom sort title would be used in "Auto" and "Title" options, right? 

I am not entirely sure what would be the best. I am thinking having a separate auto option is not necessary anymore. If I remember correctly, auto is pretty much sort by titles, but if there are numbers in the titles, we will try to sort by those numbers instead. I guess most users are using the auto mode as it's just a better version of title mode. But of course let me know what you think.

> Is it needed that a mark shows that the title has a custom sort name in an item card UI? or should we show a custom sort name in somewhere?

I think it's OK for it to stay hidden. In Plex sort title is a separate field and it won't be shown in the UI.

![DeepinScreenshot_select-area_20211224172933](https://user-images.githubusercontent.com/7845831/147340255-f98409fc-628f-4940-80b9-188970fe17cd.png)

**Comment by hkalexling** [comment]
So we will have three kind of titles

- `title`: Can only be changed by renaming the underlying file.
- `display_name`: Only used in UI, can be customized. Falls back to `title` when it's not set.
- `sort_title`: Only used when sorting, can be customized, and won't be shown in the UI. Falls back to `title` when it's not set.

**Comment by Leeingnyo** [comment]
Good! I worked with this!
