### ISSUE TITLE
[Feature Request] Add support for individual image files(jpg,png,misc.)

### ISSUE THREAD

**Issue by Sak94664** [hkalexling/Mango#189]
**Is your feature request related to a problem? Please describe.**
I have some manga/lightnovel files that I scanned myself,but the scans are all individual jpg/png files.So I need to manually compress them into individual zip files,which is a bit frustrating.
~~(Although I used a dirty script to compress them automatically)~~

**Describe the solution you'd like**
Maybe such kind of expression is more direct?(edited from wikipage)  
library structure:

.
├── Manga 1
│  ......
└── Manga 2
    └── Vol. 1
        └── Ch.1
            ├── 1.jpg
            ├── 2.jpg
            └── .....

**Describe a small use-case for this feature request**
If one have a lot image files instead of cbz/zip files,it will be more convenient for him/her to sort those files and don't need to manually compress them.

**Additional context**
Want some features in Tachiyomi local manga.XD
~~It will be better if it allows me to add description for each manga(that's too much)~~

**Comment by Sak94664** [comment]
Oops!  
duplicate of  
https://github.com/hkalexling/Mango/issues/187

**Comment by hkalexling** [comment]
Yes, the reason for not supporting this at the moment is that, if you have the technical skills to write your own scrapper to download the individual pages, you can certainly write a script to package them.
