### ISSUE TITLE
Scan find no items.

### ISSUE THREAD

**Issue by derpieler** [hkalexling/Mango#191]
Hello,

I use Mango in a docker on unraid.
Unfortunately no eBooks are imported.
I put in the in the directory /root/mango/library a few cbz documents. However, nothing is imported.
Also, I have turned on debug mode in the config. However, no errors are generated. It seems like there is nothing to do.
Does anyone have a tip on what my error could be?

Many greetings
derpieler

![2021-04-29_13h52_12](https://user-images.githubusercontent.com/52761415/116972018-bb3a8080-acba-11eb-972a-8ddb41d10d5a.png)

![2021-04-29_13h54_48](https://user-images.githubusercontent.com/52761415/116972035-bf669e00-acba-11eb-9c42-96fd105aa539.png)

**Comment by hkalexling** [comment]
Hi Please organize your cbz files into nested folders in your library. For example, create a `symmetry` folder and move the two volumes of symmetry there, and you should be able to see them.

**Comment by derpieler** [comment]
ah.
That was simple.
Many thanks.
