### ISSUE TITLE
[Feature Request] Enable support for avif

### ISSUE THREAD

**Issue by Niller303** [hkalexling/Mango#192]
**Is your feature request related to a problem? Please describe.**
As more browsers are getting native support for avif, it would be nice to also have mango support this format.
It's supported by Firefox, Chrome, and Opera.
It's not supported by Safari and Edge.

**Describe the solution you'd like**
Add image/avif to the list of supported image formats

**Describe a small use-case for this feature request**
If you are working with higher quality images, the size reduction from jpeg can be dramatic, so it would be beneficial for bandwidth and disk space savings.

**Additional context**
I also don't see why image/gif isn't supported, this is an ancient format supported by practically all browsers.
https://caniuse.com/avif

**Comment by Nerothos** [comment]
Can't avif be store in a cbz?

**Comment by Niller303** [comment]
Anything can be stored in a cbz format since its a zip file, but Mango has a hardcoded SUPPORTED_IMG_TYPES which specifies image formats Mango will recognize, and avif isn't in there.
So if you have a cbz file with avif images it won't show up in Mango because it's seen as empty.

**Comment by hkalexling** [comment]
Yes you are right. I guess there's no harm in supporting more image formats 👍

**Comment by Leeingnyo** [comment]
So, do we allow files whose mime type is `image/*`?

**Comment by hkalexling** [comment]
@Leeingnyo Yes I think we can do that. One potential issue is that, if the first page of an entry has a type not supported by [image_size.cr](https://github.com/hkalexling/image_size.cr), Mango would fail to generate the thumbnail. But this won't break anything and Mango would just serve the original file instead.
