### ISSUE TITLE
Can't login to MangaDex since new API online

### ISSUE THREAD

**Issue by dbx10** [hkalexling/Mango#193]
Since Mangadex put their new API online yesterday, attempting to login to Mangadex in Mango returns 
`Failed to log in. Error: Missing hash key: "mangadex_rememberme_token"`

I am guessing Mango is not compatible with the new API, but I will leave this as a bug as I have not looked at their new API, nor am I qualified to anyway. https://api.mangadex.org/docs.html

1. Go to Admin page
2. Click on Connect to Mangadex
3. Attempt logging in with valid creds

 - OS: Ubuntu 20.04.2 LTS
 - Accessing via Chrome
 - Mango v0.21.0 in docker

```version: '3'

services:
  mango:
    image: hkalexling/mango
    container_name: mango
    expose:
      - 9000
    ports:
      - 9001:9000
    volumes:
      - ~/mango:/root/mango
      - ~/.config/mango:/root/.config/mango

**Comment by hkalexling** [comment]
The MD API v5 is completely different, and I would need to rewrite a large chunk of Mango to keep the integration working. In fact my PR #180 is also useless now :(

There is a relevant issue at https://github.com/hkalexling/mango-plugins/issues/10, but perhaps I should move it to this repository.
