### ISSUE TITLE
[Question] Linking to Google Drive

### ISSUE THREAD

**Issue by Kyosodev** [hkalexling/Mango#195]
I'm enjoying Mango so far but I'm trying to set up the library with Google Drive and link it to my disk with rclone.
When I have the link set up and start Mango it takes ages to load the web UI. 

Does Mango load the entire library when you access the web ui?
Is there a way to only read/write files when the files are needed? For example reading or 
thumbnail generation.

Cheers,
Kyoso

**Comment by hkalexling** [comment]
Hi, thanks for trying Mango!

This is a known issue. Please see https://github.com/hkalexling/Mango/issues/118#issuecomment-720055140. 

To make Mango play well with an rcloned library, we will have to make some big changes to the scanner and the library class. I am currently focusing on the new plugin system https://github.com/hkalexling/mango-plugins/issues/7 and getting Mango to work with the new MangaDex API v5, so this has to wait :(

If you or anyone else is willing to try and take on this, please let me know! I am closing this issue for now and you can follow #118 to get updated.
