### ISSUE TITLE
[Feature Request] Cache next page

### ISSUE THREAD

**Issue by Damix48** [hkalexling/Mango#196]
**Is your feature request related to a problem? Please describe.**
I have some heavy file (the page are about 2mb each). When I use the reader via internet only one page is loaded. When I go to the next it takes some time to load it.

**Describe the solution you'd like**
Cache the 1 or more next page

**Comment by Leeingnyo** [comment]
Hi! Did you use a paged mode on the viewer? I have a similar experience on that.

**Comment by Damix48** [comment]
Yes, the paged mode don't load any of the next pages

**Comment by Leeingnyo** [comment]
Hi! It's implemented on my machine but waiting for #214 merged
