### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sanityy55** [hkalexling/Mango#198]
What are the the default log in credentials?
The documentation isn't that clear about it
It would be better if it's set as
Default username:.....
default password:.....
Thaanks

**Comment by sanityy55** [comment]
Just to make it clear I am unable to find where the randomly generated credentials are logged

**Comment by hkalexling** [comment]
Hi, Mango always logs to STDOUT. The exact log location depends on the way you started Mango. If you run the binary, the credentials will be logged to your console. If you run it in a docker container, you can check the container log.
