### ISSUE TITLE
[Bug Report] Responsive View for Menu on Website is Broken

### ISSUE THREAD

**Issue by oxr463** [hkalexling/Mango#199]
**Describe the bug**

The responsive view when opening the menu for the website on mobile is broken.

**To Reproduce**
1. Go to https://getmango.app
2. Click on the menu icon
4. See responsive issue.

**Expected behavior**

I would expect the elements to be pushed over properly, and not overlay on top of the menu.

**Environment (please complete the following information):**
 - OS: Android
 - Browser: Firefox
 - Mango Version: N/A

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.

N/A

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.

![IMG_20210605_074226](https://user-images.githubusercontent.com/43783393/120890636-1de0ae00-c5d2-11eb-8e3d-89506619508b.jpg)

**Comment by hkalexling** [comment]
Thanks for the bug report! I've fixed the issue in the website repo: https://github.com/hkalexling/mango-website
