### ISSUE TITLE
[Bug Report] Crystal link on website is broken

### ISSUE THREAD

**Issue by oxr463** [hkalexling/Mango#200]
**Describe the bug**

The link to the Crystal website from the Mango website is broken.

**To Reproduce**
1. Go to https://getmango.app
2. Click on "Crystal"
4. See 404 page

**Expected behavior**

Instead of redirecting to https://crystal-lang.org, it goes to https://getmango.app/#/crystal-lang.org, which doesn't exist.

**Environment (please complete the following information):**
 - OS: Android
 - Browser: Firefox
 - Mango Version: N/A

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.

N/A

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.

N/A

**Comment by hkalexling** [comment]
Fixed in the website repo: https://github.com/hkalexling/mango-website. Thanks for the heads up!
