### ISSUE TITLE
[Feature Request] Add Kavita to Wiki for Alternatives

### ISSUE THREAD

**Issue by majora2007** [hkalexling/Mango#207]
Please add Kavita (https://github.com/Kareadita/Kavita) to the Wiki. I tried cloning repo and wiki, but I was unable to push my feature branch up.

Kavita is an open source alternative which handles Manga, Comics, eBooks.

**Comment by hkalexling** [comment]
Oh, I had to disable public edit on the wiki to stop random spammers. I've added Kavita to the list. Thanks for the suggestion, and all the best to the project!
