### ISSUE TITLE
[Question] [HELP] Installation On Windows

### ISSUE THREAD

**Issue by alexpandain** [hkalexling/Mango#208]
To Reproduce:

1. Downloaded `Mango` file from Release page
2. Open CMD
3. `cd C:/Mango Server`
4. Run `Mango`
 
Error: `'mango' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by hkalexling** [comment]
There's no native windows support at this moment. You can either run Mango in WSL or use Docker. See https://github.com/hkalexling/Mango/wiki/Platform-Support
