### ISSUE TITLE
[Feature Request] Option to disable page spacing

### ISSUE THREAD

**Issue by tr7zw** [hkalexling/Mango#211]
**Is your feature request related to a problem? Please describe.**
Some Mangas are designed to have no space between the pages/the pages are cut in odd places. In the current continuous setting this causes a gap between these pages.

**Describe the solution you'd like**
A 3rd option in the viewer that doesn't have the gap between two pages in continuous mode.

**Comment by hkalexling** [comment]
This is already possible since https://github.com/hkalexling/Mango/pull/136. In the dev branch, the setting can be adjusted on the fly through the web UI, but I still need some time to polish other features before releasing it.

**Comment by tr7zw** [comment]
Ah ok. since I'm not on the dev branch I wasn't aware. Might give that branch a try in a separated container.
