### ISSUE TITLE
[Feature Request] Want to support GIF format

### ISSUE THREAD

**Issue by zyx134** [hkalexling/Mango#228]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe a small use-case for this feature request**
How would you imagine this to be used? What would be the advantage of this for the users of the application?

**Additional context**

**Comment by zyx134** [comment]
Want to support GIF format pictures

**Comment by hkalexling** [comment]
This has been added in #225 and is now available in `dev`. We will merge it to `master` and make an official release soon.

**Comment by zyx134** [comment]
thanks
