### ISSUE TITLE
adjust the display title length and cover size

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#23]
**Is your feature request related to a problem? Please describe.**
Some manga have a long title length same as a light novel:) Hence display the full title is not a good choice. And the manga cover size have the same problem, because of the different size of manga's first image. It could be too wide or too short

**Describe the solution you'd like**
create a unified display length and size for title and cover

**Additional context**
Such as Komga, it's a good example on this problem

**Comment by DuraMorte** [comment]
This sounds virtually identical to #20.

**Comment by WROIATE** [comment]
> This sounds virtually identical to #20.

There have some differences that I want to change the display size of cover with css but you'd like to change the cover's URL. Also I want to shorten title length use ellipsis like Komga and don't want rename it. In other words, it is not a same issue.

**Comment by hkalexling** [comment]
> I want to shorten title length use ellipsis like Komga

I agree this would improve the user experience. I will work on it soon.

> because of the different size of manga's first image. It could be too wide or too short

We do have a [CSS rule](https://github.com/hkalexling/Mango/blob/master/public/css/mango.css#L7-L10) to restrict the maximum height of the thumbnails. Is this what you are looking for? It would be great if you could provide a more concrete example (preferably with screenshots).

**Comment by WROIATE** [comment]
> > I want to shorten title length use ellipsis like Komga
> 
> I agree this would improve the user experience. I will work on it soon.
> 
> > because of the different size of manga's first image. It could be too wide or too short
> 
> We do have a [CSS rule](https://github.com/hkalexling/Mango/blob/master/public/css/mango.css#L7-L10) to restrict the maximum height of the thumbnails. Is this what you are looking for? It would be great if you could provide a more concrete example (preferably with screenshots).

For example:
**This is Komga**
![Snipaste_2020-03-29_17-08-13](https://user-images.githubusercontent.com/44677306/77845257-017fff00-71e0-11ea-9152-19b55589c1f1.png)
**This is Mango**
![Snipaste_2020-03-29_17-07-13](https://user-images.githubusercontent.com/44677306/77845260-02b12c00-71e0-11ea-912d-7f4639931ad5.png)

I think it's a good idea to resize the cover. And you could display the left half image of the long picture by checking the origin picture size.

**Comment by hkalexling** [comment]
Thanks for the clarification.

I don't think what Komga does is very elegant. In your screenshot, the second half of the title is missing, and the image resolution if low because only a portion of it is shown. I think it would be better to keep it this way, but add #20 so you can manually upload a cover image with the desired size.

**Comment by WROIATE** [comment]
> Thanks for the clarification.
> 
> I don't think what Komga does is very elegant. In your screenshot, the second half of the title is missing, and the image resolution if low because only a portion of it is shown. I think it would be better to keep it this way, but add #20 so you can manually upload a cover image with the desired size.

I guess Komga generate a thumbnail make it so blurry, in fact the picture resolution is high...

Sometimes this cover displayed too small  (like mobile devices) that can't see anything and will create a huge gap between the two pictures like this:
![Snipaste_2020-03-30_18-44-18](https://user-images.githubusercontent.com/44677306/77904088-82a9c580-72b6-11ea-9a95-18e89e449836.png)
How about resize it with **same height**? such as:
![Snipaste_2020-03-30_18-35-24](https://user-images.githubusercontent.com/44677306/77903641-c64fff80-72b5-11ea-9f1c-5cee53be5ad4.png)
Also it looks good on the mobile devices：
![Snipaste_2020-03-30_18-35-55](https://user-images.githubusercontent.com/44677306/77903828-1929b700-72b6-11ea-9fea-7b965b51bc4d.png)

**Comment by hkalexling** [comment]
This looks nice! I will try it out and see how it works. 

Do you mind sharing the CSS you used to get the result? Again feel free to submit a PR to the `dev` branch if you want.

**Comment by WROIATE** [comment]
> This looks nice! I will try it out and see how it works.
> 
> Do you mind sharing the CSS you used to get the result? Again feel free to submit a PR to the `dev` branch if you want.

Unfortunately, the css style I just use chrome to edit the single div element but not code a css file for web.

**Comment by hkalexling** [comment]
@WROIATE Just to keep you updated, I tried the fixed height strategy you proposed. Unfortunately in most cases it doesn't produce the great result as shown in your screenshots above.

I then tried the Komga approach and it's actually much better than I thought:

Before:
![Screen Shot 2020-04-01 at 12 58 51 PM](https://user-images.githubusercontent.com/7845831/78101411-04663400-741a-11ea-8f2d-af9e742b94a8.png)

After:
![Screen Shot 2020-04-01 at 12 55 57 PM](https://user-images.githubusercontent.com/7845831/78101399-fd3f2600-7419-11ea-9508-1de1ccc162d8.png)

In the second screenshot, we fix the height of the cover images and titles, so the cards have the exact same size and the overall layout is much cleaner. But of course, the trade-off is that sometimes only the center part of the cover image is visible. 

I will probably tweak it a bit more and make a new release soon. Feel free to let me know what you think!

**Comment by WROIATE** [comment]
> @WROIATE Just to keep you updated, I tried the fixed height strategy you proposed. Unfortunately in most cases it doesn't produce the great result as shown in your screenshots above.
> 
> I then tried the Komga approach and it's actually much better than I thought:
> 
> Before:
> ![Screen Shot 2020-04-01 at 12 58 51 PM](https://user-images.githubusercontent.com/7845831/78101411-04663400-741a-11ea-8f2d-af9e742b94a8.png)
> 
> After:
> ![Screen Shot 2020-04-01 at 12 55 57 PM](https://user-images.githubusercontent.com/7845831/78101399-fd3f2600-7419-11ea-9508-1de1ccc162d8.png)
> 
> In the second screenshot, we fix the height of the cover images and titles, so the cards have the exact same size and the overall layout is much cleaner. But of course, the trade-off is that sometimes only the center part of the cover image is visible.
> 
> I will probably tweak it a bit more and make a new release soon. Feel free to let me know what you think!


Perhaps left justify the long image in the container or crop it in the web backstage will solve the display question of center part cover. You could identify the long picture at backstage and switch the display way.

**Comment by hkalexling** [comment]
> Perhaps left justify the long image in the container or crop it in the web backstage will solve the display question of center part cover.

This might not work in some cases (see the following screenshot). I think I will leave it like this for now. I will work on #20 soon, and once the feature is added, you can simply upload a cover image with the desired size. 

<img src="https://user-images.githubusercontent.com/7845831/78217825-5af17200-74ef-11ea-9f9d-a81d973caf6c.png" width="250px">

The requested features in this issue are now available in [v0.2.4](https://github.com/hkalexling/Mango/releases/tag/v0.2.4) so I am closing this. Feel free to reopen if needed.
