### ISSUE TITLE
[Bug Report] Default login not given on first startup

### ISSUE THREAD

**Issue by HSAK5G** [hkalexling/Mango#234]
**Describe the bug**
When I start mango for the first time there is no login info.

**To Reproduce**
1. Start mango
2. No login

**Expected behavior**
There is meant to be a login

**Environment (please complete the following information):**
 - OS: Windows 10 WSL Ubunu 20.04
 - Mango Version : 0.23.0

**Comment by Leeingnyo** [comment]
Mango would print auth info to its STDOUT at initial start. See https://github.com/hkalexling/Mango#initial-login. Check your terminal or container logs please. If you lost them, remove `mango.db` and restart please.
