### ISSUE TITLE
[Feature Request] Covers don't allow the uploading of gifs

### ISSUE THREAD

**Issue by tr7zw** [hkalexling/Mango#235]
**Is your feature request related to a problem? Please describe.**
When selecting a manga cover image, you can't use .gif files. They are not shown by default, and using "All files" to select it, it won't be uploaded or applied. But placing the gif in the uploads/img folder and adding it in the info.json works perfectly fine.

![4WMrcocPqX](https://user-images.githubusercontent.com/5133936/134247041-44afb68b-50b5-47dd-9176-9b3e60a9d082.gif)

**Describe the solution you'd like**
Add gif as an accepted cover format.

**Comment by hkalexling** [comment]
Hi, GIF support will be available in v0.24.0. We will make a release soon, or you can try out the beta build at #232.

**Comment by tr7zw** [comment]
Ah I did see that, but thought this was just in regards to files inside the zip, not for the cover upload too. Thanks for clarifying.
