### ISSUE TITLE
Where can I find the built-in Mangadex download manager?

### ISSUE THREAD

**Issue by urcades** [hkalexling/Mango#239]
I may be incredibly dense, or just missing something, but I can't seem to find any hint of where I might go about downloading from mangadex — I paged through every available bit of the interface!

Can someone help me out here? Maybe provide a screenshot/relative path for where I could expect to find this interface?

Edit: I'm on version `v0.24.0`

**Comment by Nerothos** [comment]
See #170 , it's being worked on in a way to remove mangadex content from mango to put it in a plugins

**Comment by hkalexling** [comment]
Yeah, the MangaDex integration has been broken because of their new API. We are redesigning the plugin system and will move the MangaDex integration into an official plugin.
