### ISSUE TITLE
[Feature Request] Read Comic Title from ComicInfo.xml

### ISSUE THREAD

**Issue by Cygon** [hkalexling/Mango#241]
**Is your feature request related to a problem? Please describe.**
Currently, Mango uses the file name of a .cbz or .cbr as the displayed title of a manga of comic book, which I then have to manually update via the UI.

There are several competing standards, but a popular way of storing the comic title and other informations in .cbz and .cbr files is via an embedded `ComicInfo.xml` file. It follows this format:

```xml
<?xml version="1.0"?>
<ComicInfo>
  <Title>My Awesome Comic</Title>
  <!-- Other nodes like Genre, PageCount, BlackAndWhite, RightToLeft, Characters... -->
</ComicInfo>
```

It would be very nice if Mango could check for the presence of a `ComicInfo.xml` and read the `Title` node to use as a manga's title.

**Describe the solution you'd like**
I would like for Mango to check if a `ComicInfo.xml` exists in a newly imported `.cbz`, `.cbr` or `.zip` file and to read the `Title` node to use as the display title of the book. If either is missing, fall back to the file name.

**Describe a small use-case for this feature request**
I've got a rather well populated library of manga and comics that I'd like to import into Mango.

My files are named for easy handling, i.e. all lowercase and without non-ascii-characters, so with the current behaviour, all book titles would be like this, too. Manually fixing them all via the UI takes forever.

Since all my books have a `ComicInfo.xml` file, if Mango would take the title from there, I could just move my entire library folder over to Mango and everything would work out.

**Comment by hkalexling** [comment]
Hi, thanks for the feature request! It looks like what you are proposing is a subset of #194 so I will be closing this. Please subscribe to that issue to get updated.
