### ISSUE TITLE
[Bug Report] Can't click on the menu buttons while not in a maximized browser window

### ISSUE THREAD

**Issue by DisableGraphics** [hkalexling/Mango#246]
**Describe the bug**
I can't click on the mango menu buttons only if the browser window is not maximized.
If it's maximized, it works perfectly fine.

**To Reproduce**

Resize the window browser (In my case a more or less vertical window) and click the menu buttons

**Expected behavior**

The buttons should be possible to click while not in maximized window mode

**Environment (please complete the following information):**
 - OS: ArcoLinux (Archlinux-based)
 - Browser: Waterfox (Firefox fork)
 - Mango Version: 0.24.0

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.
This menu:
![mangomenu](https://user-images.githubusercontent.com/48135147/136670954-7b8b5953-ee16-4fd1-a40a-4adf951c292d.png)

Good work with the 0.24.0 update, though! The caching option does wonders, and works perfectly with my enormous library

**Comment by hkalexling** [comment]
Ah yes I can reproduce this. Will try to fix this in the next release. Thanks for the bug report!
