### ISSUE TITLE
I hope you can specify different directories for different people.

### ISSUE THREAD

**Issue by akimolll** [hkalexling/Mango#250]
![1111](https://user-images.githubusercontent.com/1827701/140980124-7884299f-b645-421a-9690-03da6bedcb34.jpg)

Whether to allow the administrator to specify different directories for each user and let the administrator decide what each user can see. It doesn't seem to be a good idea to present everything in front of different types of people, especially for child users.
If the administrator makes the decision, everything will be in order.

I drew the picture above, which seems easier to describe the intention.

**Comment by hkalexling** [comment]
Thanks for the feature request. What you described is very close to #13 so I am going to close it. Please subscribe to that thread to get updated.

**Comment by Leeingnyo** [comment]
How about using the Mango like this if you want to preserve a one home folder?
There is a one real library directory that has all manga folders, and two directories that are for two Mango instances each, which have manga folders symlinked with which in real directory

- Real Library
  - A
  - B
  - C

- Virtual Library for children
 - symlinked A
- Virtual Library for young, adult
 - symlinked B
 - symlinked C

I use docker to run Mango and use volume and symlinks for adding manga files.
