### ISSUE TITLE
[Feature Request] Whether to consider making some richer experience content for the login interface.

### ISSUE THREAD

**Issue by akimolll** [hkalexling/Mango#251]
![Snipaste_2021-11-10_02-12-57](https://user-images.githubusercontent.com/1827701/140981041-622bda08-8e50-4094-ac30-66714eced611.png)

Now the dull login interface seems to bring some gloom to the mood😂. There is really no room to enrich and improve.

![Snipaste_2021-11-10_02-13-16](https://user-images.githubusercontent.com/1827701/140981295-3067c90f-6841-4688-8396-c3d5620441e6.png)
This is inspired by: https://github.com/navidrome/navidrome Demo： https://demo.navidrome.org/app/ https://www.navidrome.org/demo/
It allows users to see some pleasing pictures every time they log in, and they will be in a good mood.

I was wondering if I could consider adding a custom background function. Or randomly quote some book images or cartoon images from unsplash, so that users will become rich, interesting and different every time they log in.

**Comment by hkalexling** [comment]
Thanks for the feature request. I don't think showing a random image from a manga is a good idea. There might be inappropriate content that you don't want to share with the public.

I do agree that a custom background could be nice to have, provided that it's disabled by default, but I guess not many users would need this feature so it would have a low priority on my list. But of course, you are always welcome to submit a PR if you or anyone else is interested in working on this.
