### ISSUE TITLE
[Feature Request] Reader additional buttons / info

### ISSUE THREAD

**Issue by duckimann** [hkalexling/Mango#253]
**Is your feature request related to a problem? Please describe.**
It's kinda frustrated when you reached the end of and manga and the only button to click is "Next Entry" and show no info about the current chapter

**Describe the solution you'd like**
It should have buttons to go to
- Home (go to the Home)
- Manga Details
- Previous Chapter

It should have a header like h1 or something to show current manga and current chapter

**Comment by hkalexling** [comment]
When you click on any page in the chapter you will get a modal showing you the chapter info. You can also jump to other chapters from there.

![Screenshot 2021-11-18 at 11 01 58 AM](https://user-images.githubusercontent.com/7845831/142344100-d7993b65-ecbc-42e1-8624-391915723a4d.png)
