### ISSUE TITLE
[Bug Report] Incorrectly truncated titles and incorrect page count

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#26]
**Describe the bug**
1. The title display on chrome will be failed with "..."
2. The page number display "2" when the comic only have one page 

**To Reproduce**
1. Go to chrome with mango v0.2.5
2. See error

**Environment (please complete the following information):**
 - OS:Unraid 6.8.1
 - Browser: chrome
 - Mango Version: v0.2.5

**Docker (if you are running Mango in a Docker container)**
```
FROM crystallang/crystal:0.32.1-alpine AS builder

WORKDIR /Mango

RUN wget https://github.com/hkalexling/Mango/archive/v0.2.5.zip \
    && unzip v0.2.5.zip

WORKDIR /Mango/Mango-0.2.5

RUN apk add --no-cache yarn yaml sqlite-static \
    && make static

FROM library/alpine

WORKDIR /

COPY --from=builder /Mango/Mango-0.2.5/mango .

CMD ["./mango"]
```
**Additional context**
![Snipaste_2020-04-04_23-49-10](https://user-images.githubusercontent.com/44677306/78455409-c9d9f100-76d0-11ea-87cb-536467c4610c.png)

**Comment by hkalexling** [comment]
> The title display on chrome will be failed with "..."

Please clear the browser cache and then reload the page.

> The page number display "2" when the comic only have one page

I cannot reproduce this:

<img width="281" alt="Screen Shot 2020-04-05 at 6 39 18 AM" src="https://user-images.githubusercontent.com/7845831/78462826-6cfa2d00-7708-11ea-84ae-3f378f79125c.png">

Could you show me the content of your zip file or send it to me?

BTW it looks like you are using a custom userscript to get the dark interface. You might want to try out the built-in dark mode in Mango. It looks much better.

**Comment by WROIATE** [comment]
@hkalexling 
I found the problem of page number is that my mac generated a hide file...
```
Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   227097  03-30-2020 18:28   1_hmsbudcj.jpg
        0  03-30-2020 18:28   __MACOSX/
      186  03-30-2020 18:28   __MACOSX/._1_hmsbudcj.jpg
---------                     -------
   227283                     3 files
```
But the title is also cannot display the correct title even I clear the chrome cache

**Comment by WROIATE** [comment]
It's working on firefox but not chrome
![Snipaste_2020-04-05_16-01-39](https://user-images.githubusercontent.com/44677306/78469786-cf7a1a00-7756-11ea-9470-5a1e37840b3b.png)
![Snipaste_2020-04-05_16-01-28](https://user-images.githubusercontent.com/44677306/78469785-cdb05680-7756-11ea-949a-ba016c9995d3.png)

**Comment by hkalexling** [comment]
May I know the Chrome version you are using? And can you try it again in incognito mode without enabling any extensions? I tried it in multiple versions of Chrome on all my devices but still can't reproduce the bug.

**Comment by WROIATE** [comment]
> May I know the Chrome version you are using? And can you try it again in incognito mode without enabling any extensions? I tried it in multiple versions of Chrome on all my devices but still can't reproduce the bug.

The chrome for mac version is 80.0.3987.149 
I have tried the incognito mode. Unfortunately, the same problem happened
![Snipaste_2020-04-05_16-09-35](https://user-images.githubusercontent.com/44677306/78469979-4c59c380-7758-11ea-80f4-955acf18840e.png)

**Comment by hkalexling** [comment]
Still, I can't reproduce it :(

Hi @ermus19, you mentioned in Gitter that you had the same problem. Have you found the cause? Did it happen again? Thanks!

**Comment by hkalexling** [comment]
@WROIATE Is there a way for me to contact you privately? To isolate the problem, I can send you the login information to my test server so you can test to see if the problem persists.

**Comment by ermus19** [comment]
Hello! 

So, as I told @hkalexling on gitter, I also faced this issue after upgrading to v0.2.5
Could not get rid of it even after deleting browsing data, going incognito etc. However, it was still working fine on Firefox.

**What I did**: delete all browsing data (cookies, site data) on Chrome and **reboot the computer.**
After doing so, titles were no longer truncated. Also, I realised it was due to browser because I asked another of my network user's to load the page using Chrome and issue was not present there (also tested using Android Chrome).

Hope it helps!

**Comment by WROIATE** [comment]
> Hello!
> 
> So, as I told @hkalexling on gitter, I also faced this issue after upgrading to v0.2.5
> Could not get rid of it even after deleting browsing data, going incognito etc. However, it was still working fine on Firefox.
> 
> **What I did**: delete all browsing data (cookies, site data) on Chrome and **reboot the computer.**
> After doing so, titles were no longer truncated. Also, I realised it was due to browser because I asked another of my network user's to load the page using Chrome and issue was not present there (also tested using Android Chrome).
> 
> Hope it helps!

Good job! It's useful I clear the cookie and data with all time range!
