### ISSUE TITLE
[Feature Request] Admin can move tagged subjects to trash folder

### ISSUE THREAD

**Issue by Evlos** [hkalexling/Mango#263]
**Is your feature request related to a problem? Please describe.**
Admin should be able to move manga to trash folder

**Describe the solution you'd like**
Automatically create a trash folder under library folder e.g. _trash.
Maybe provide a trash button on tag list and library view to move selected manga to trash folder.

**Describe a small use-case for this feature request**
After we read a manga, we can keep it if we like, but there always some mangas we would like to delete.

**Additional context**

**Comment by hkalexling** [comment]
Hey thanks for the feature request!

Your Mango library is directly mapped from your file system. Each folder is a title (also called a manga or a series) and each cbz/cbr file is an entry (aka a chapter). To delete a manga you can simply delete the folder form your file system. Using the file system itself to manage files is much more elegant that hacking our own solution IMHO.

**Comment by Evlos** [comment]
All right, thank you for reply.
