### ISSUE TITLE
[Bug Report] Redirected to /api/admin/thumbnail_progress when docker container is restarted while on admin page

### ISSUE THREAD

**Issue by BradleyDS2** [hkalexling/Mango#267]
**Describe the bug**
As discussed in #265:
"When you visit any page without a valid auth token, Mango redirects you to the login page, and after a successful login you will be redirected back to the page you requested. In your case, you were still on the admin page when the container restarted, and the browser was still sending requests to the progress endpoint. So when the container came back online you were sent to the login page and then redirected to the page you last requested, which happened to be the JSON API."

**To Reproduce**
1. Go to the Admin page
2. Restart the docker container
3. Log in

**Expected behavior**
Sent to homepage or admin page

**Environment (please complete the following information):**
 - OS: Unraid
 - Browser: Firefox
 - Mango Version: 0.24.0

**Docker**
Default values, other than:
- Map /Manga in container to /mnt/user/manga/ in host
- Map /root/.config/mango in container to /mnt/user/appdata/Mango/Config in host
- Map /root/mango in container to /mnt/user/appdata/Mango/Appdata in host

**Additional context**
It may be best to redirect to the home page after logging in, generally speaking, as otherwise if a container is stopped, then the files are modified, when container is started again the client could experience an error.
Example would be the client is reading a manga, the container is stopped, the manga is deleted, then the container is resumed.

This bug is very minor with minimal user impact.

**Comment by hkalexling** [comment]
This is not a bug but a design choice. In most cases this is a very useful feature - I can just reload the page, log in, and then continue from where I was. The situations you described and encountered in #265 are relatively rare so I don't really want to sacrifice this feature.

**Comment by BradleyDS2** [comment]
Perfectly understandable, it's a rare circumstance and has minimal impact.
