### ISSUE TITLE
[Bug Report] Generate Thumbnails stuck

### ISSUE THREAD

**Issue by ryanmichaelmcclure** [hkalexling/Mango#270]
Yesterday, I noticed that under Admin, Generate Thumbnails was stuck at 68%. Strange. I didn't think anything of it.

Today, it's still stuck at the same percentage. I'm also unable to click on Generate Thumbnails, which I'm attempting to do to fix the thumbnails for a series. I've tried restarting my Docker container, and still no luck. Any thoughts?

**Comment by hkalexling** [comment]
Can you set log level to debug and paste the log here?

For future reference, it's better to follow the issue templates when opening issues. If you want a casual discussion use https://github.com/hkalexling/Mango/discussions instead.

**Comment by ryanmichaelmcclure** [comment]
Sorry for putting it in the wrong label, I thought it was an bug since this wasn't expected behavior

Here's a link to the log: https://pastebin.com/UAHAQjjm

Here's a screenshot of what I'm seeing: https://i.imgur.com/pYiNLwV.png

**Comment by hkalexling** [comment]
Ah yes this does look like a bug. My point is when creating bug reports it's better to follow the template ;-)

![DeepinScreenshot_select-area_20220126100458](https://user-images.githubusercontent.com/7845831/151091529-5b0a2562-4bf9-4daa-ac5d-8c141786d18d.png)

Anyway can you try deleting the `library.yml.gz` file in the main folder (by default it's `~/mango/library.yml.gz` on unix) and then restart? This is a temporary cache of your library and it's likely causing the issue.

**Comment by ryanmichaelmcclure** [comment]
I see. I've not done much on Github before and I'm still learning. Thanks for showing me where that is!!!

That did it! Looks like deleting library.yml.gz rebuilds everything. It now shows 100% after a full rebuild when clicking on it, and it is no longer grayed out. Looks like that was the fix. Thanks!
