### ISSUE TITLE
[Bug Report] Download not added to queue

### ISSUE THREAD

**Issue by BradleyDS2** [hkalexling/Mango#275]
**Describe the bug**
Using the nHentai plugin, a specific 'manga' cannot be downloaded. Unknown if this affects others.
When attempting to download, the following message is received: "0 of 1 chapters added to the download queue. You can view and manage your download queue on the download manager page."

**To Reproduce**
1. Go to the Plugins page and select nHentai
2. Enter 'https://nhentai.net/g/244327/' as the address
3. Select the result and attempt to download it

**Expected behavior**
Download should add to the queue

**Environment (please complete the following information):**
 - OS: Unraid
 - Browser: Firefox
 - Mango Version: 0.24.0

**Docker**
Default values, other than:
- Map /Manga in container to /mnt/user/manga/ in host
- Map /root/.config/mango in container to /mnt/user/appdata/Mango/Config in host
- Map /root/mango in container to /mnt/user/appdata/Mango/Appdata in host

**Additional context**
![image](https://user-images.githubusercontent.com/2174921/151803733-caf95683-72bf-461d-8e3b-5a6cbadefc0e.png)
![image](https://user-images.githubusercontent.com/2174921/151803764-1b0356db-1ee9-419c-ac4d-257cecde0e85.png)
![image](https://user-images.githubusercontent.com/2174921/151803800-7ce74625-72a4-48c7-8bc0-7c72a480cdc2.png)

When this failed, I tried downloading something else from nHentai, and it was successful. I then re-attempted this and it failed again.

Debug logs show nothing of value:
```
[96m[DEBUG] [0m2022/01/31 13:41:23 | Setting proxy
[96m[DEBUG] [0m2022/01/31 13:41:23 | Setting read timeout
[96m[DEBUG] [0m2022/01/31 13:41:23 | Requesting https://nhentai.net/g/244327/
[96m[DEBUG] [0m2022/01/31 13:41:23 | Performing request
[96m[DEBUG] [0m2022/01/31 13:41:24 | 200 GET /api/admin/plugin/list?query=https%3A%2F%2Fnhentai.net%2Fg%2F244327%2F&plugin=nhentai 451.43ms
[96m[DEBUG] [0m2022/01/31 13:41:27 | 200 POST /api/admin/plugin/download 15.77ms
```

**Comment by hkalexling** [comment]
It's probably because you have a job with the same ID in the download queue. Can you delete the job and then try again?

**Comment by BradleyDS2** [comment]
🤦
Sorry, not sure how that happened, closing the issue.

On the note of deleting the job, it seems I can't delete completed downloads from the queue either. Updating the title of my other issue to reflect this.

**Comment by hkalexling** [comment]
Yeah I agree we can improve the message a bit. Will take a look. Thanks for the suggestion.
