### ISSUE TITLE
[Bug Report] crashing Thumbnail generator - Unhandled exception

### ISSUE THREAD

**Issue by B17C0D3** [hkalexling/Mango#281]
**Describe the bug**
Thumbnail generator is crashing. I con't find which file is cousing the crash.

**Environment (please complete the following information):**
 - OS: Unraid 6.9.2
 - Browser Chrome
 - Mango Version v0.25.0

**Docker (if you are running Mango in a Docker container)**
- Running the docker on Unraid server, i dont know how to provide the config.

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.

Part of the Debug log:
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit /root/mango/library/temp2/Yowai 5000-nen no Soushoku Dragon, Iware naki Jaryuu Nintei:info.json
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache cached 57c0d4f0b3734e7a87248161db0b76b5:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache miss e783049253434845b3869d4e153c3259:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit /root/mango/library/temp2/Yuko Sae Tatakaeba:info.json
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache cached e783049253434845b3869d4e153c3259:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache miss d49424a345f14b5e857a0e0b203cb3bb:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit /root/mango/library/temp2/Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku o Ketsuishimashita:info.json
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache cached d49424a345f14b5e857a0e0b203cb3bb:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache miss 7232b851d9d640758a319609be6cb77c:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit /root/mango/library/temp2/Zoku, Kono Subarashii Sekai ni Bakuen wo!:info.json
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache cached 7232b851d9d640758a319609be6cb77c:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache cached 9291ee090d584f939295c7eadf5fa7ab:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit 8962527bd708445e84edaf4e468a6e9f:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit eae5c9165cf84fdebdc3e0b3ec03caad:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit 6cbf56def065446db62ef75052a0e9ef:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit c065c935192c4e9084c5b6a7f24dcc25:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit 2012b4b7e9464d0da5e11dd69e18f4b7:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | LRUCache hit 9291ee090d584f939295c7eadf5fa7ab:admin:progress_sum
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET / 861.45ms
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /js/common.js 34.52µs
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /css/mango.css 5.35ms
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /js/dots.js 16.49µs
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /js/alert.js 14.31µs
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /js/title.js 50.1µs
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /img/icon.png 103.71µs
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /img/nav-parent-close.svg 12.76µs
[96m[DEBUG] [0m2022/02/23 22:57:12 | 200 GET /webfonts/fa-solid-900.woff2 155.9µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /admin 23.12ms
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /js/common.js 16.78µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /css/mango.css 2.79ms
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /js/admin.js 30.29µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /img/icon.png 134.42µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /img/nav-parent-close.svg 11.84µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /img/form-select.svg 11.85µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /webfonts/fa-solid-900.woff2 151.61µs
[96m[DEBUG] [0m2022/02/23 22:57:15 | 200 GET /api/admin/thumbnail_progress 4.09ms
[96m[DEBUG] [0m2022/02/23 22:57:20 | 200 GET /api/admin/thumbnail_progress 3.63ms
[96m[DEBUG] [0m2022/02/23 22:57:25 | 200 GET /api/admin/thumbnail_progress 3.37ms
[96m[DEBUG] [0m2022/02/23 22:57:30 | 200 GET /api/admin/thumbnail_progress 3.89ms
[96m[DEBUG] [0m2022/02/23 22:57:35 | 200 GET /api/admin/thumbnail_progress 3.35ms
[96m[DEBUG] [0m2022/02/23 22:57:40 | 200 GET /api/admin/thumbnail_progress 3.52ms
[96m[DEBUG] [0m2022/02/23 22:57:45 | 200 GET /api/admin/thumbnail_progress 2.42ms
[93m[INFO] [0m2022/02/23 22:57:46 | Starting thumbnail generation
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /admin 24.63ms
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /css/mango.css 861.04µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /js/common.js 84.13µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /js/admin.js 53.16µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /img/icon.png 120.43µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /img/nav-parent-close.svg 47.17µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /img/form-select.svg 29.95µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /webfonts/fa-solid-900.woff2 219.15µs
[96m[DEBUG] [0m2022/02/23 22:57:48 | 200 GET /api/admin/thumbnail_progress 4.47ms
Unhandled exception in spawn: deflate: invalid stored block lengths (Compress::Deflate::Error)

from usr/share/crystal/src/compress/deflate/reader.cr:111:15 in 'unbuffered_read'
from usr/share/crystal/src/io/buffered.cr:80:16 in 'read'
from usr/share/crystal/src/compress/zip/checksum_reader.cr:12:20 in 'read'
from usr/share/crystal/src/io.cr:521:7 in 'read_entry'
from Mango/src/library/entry.cr:150:7 in 'read_page'
from Mango/src/library/entry.cr:269:11 in 'generate_thumbnails'
from Mango/src/library/library.cr:114:11 in '->'
from usr/share/crystal/src/primitives.cr:255:3 in 'run'
from ???
[96m[DEBUG] [0m2022/02/23 22:57:53 | 200 GET /api/admin/thumbnail_progress 3.49ms
[96m[DEBUG] [0m2022/02/23 22:57:56 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:57:58 | 200 GET /api/admin/thumbnail_progress 3.96ms
[96m[DEBUG] [0m2022/02/23 22:58:03 | 200 GET /api/admin/thumbnail_progress 3.61ms
[96m[DEBUG] [0m2022/02/23 22:58:06 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:58:08 | 200 GET /api/admin/thumbnail_progress 2.95ms
[96m[DEBUG] [0m2022/02/23 22:58:13 | 200 GET /api/admin/thumbnail_progress 3.72ms
[96m[DEBUG] [0m2022/02/23 22:58:16 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:58:18 | 200 GET /api/admin/thumbnail_progress 3.56ms
[96m[DEBUG] [0m2022/02/23 22:58:23 | 200 GET /api/admin/thumbnail_progress 2.37ms
[96m[DEBUG] [0m2022/02/23 22:58:26 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:58:28 | 200 GET /api/admin/thumbnail_progress 4.18ms
[96m[DEBUG] [0m2022/02/23 22:58:33 | 200 GET /api/admin/thumbnail_progress 3.62ms
[96m[DEBUG] [0m2022/02/23 22:58:36 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:58:38 | 200 GET /api/admin/thumbnail_progress 1.74ms
[96m[DEBUG] [0m2022/02/23 22:58:43 | 200 GET /api/admin/thumbnail_progress 3.02ms
[96m[DEBUG] [0m2022/02/23 22:58:46 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:58:48 | 200 GET /api/admin/thumbnail_progress 2.85ms
[96m[DEBUG] [0m2022/02/23 22:58:53 | 200 GET /api/admin/thumbnail_progress 3.33ms
[96m[DEBUG] [0m2022/02/23 22:58:56 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:58:58 | 200 GET /api/admin/thumbnail_progress 4.09ms
[96m[DEBUG] [0m2022/02/23 22:59:03 | 200 GET /api/admin/thumbnail_progress 3.47ms
[96m[DEBUG] [0m2022/02/23 22:59:06 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:59:08 | 200 GET /api/admin/thumbnail_progress 3.06ms
[96m[DEBUG] [0m2022/02/23 22:59:13 | 200 GET /api/admin/thumbnail_progress 3.35ms
[96m[DEBUG] [0m2022/02/23 22:59:16 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:59:18 | 200 GET /api/admin/thumbnail_progress 3.79ms
[96m[DEBUG] [0m2022/02/23 22:59:23 | 200 GET /api/admin/thumbnail_progress 4.05ms
[96m[DEBUG] [0m2022/02/23 22:59:26 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:59:28 | 200 GET /api/admin/thumbnail_progress 2.3ms
[96m[DEBUG] [0m2022/02/23 22:59:33 | 200 GET /api/admin/thumbnail_progress 2.86ms
[96m[DEBUG] [0m2022/02/23 22:59:36 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:59:38 | 200 GET /api/admin/thumbnail_progress 3.56ms
[96m[DEBUG] [0m2022/02/23 22:59:43 | 200 GET /api/admin/thumbnail_progress 3.8ms
[96m[DEBUG] [0m2022/02/23 22:59:46 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:59:48 | 200 GET /api/admin/thumbnail_progress 3.69ms
[96m[DEBUG] [0m2022/02/23 22:59:53 | 200 GET /api/admin/thumbnail_progress 3.86ms
[96m[DEBUG] [0m2022/02/23 22:59:56 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 22:59:58 | 200 GET /api/admin/thumbnail_progress 2.65ms
[96m[DEBUG] [0m2022/02/23 23:00:03 | 200 GET /api/admin/thumbnail_progress 3.9ms
[96m[DEBUG] [0m2022/02/23 23:00:06 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:00:08 | 200 GET /api/admin/thumbnail_progress 3.38ms
[96m[DEBUG] [0m2022/02/23 23:00:13 | 200 GET /api/admin/thumbnail_progress 3.72ms
[96m[DEBUG] [0m2022/02/23 23:00:16 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:00:18 | 200 GET /api/admin/thumbnail_progress 3.9ms
[96m[DEBUG] [0m2022/02/23 23:00:23 | 200 GET /api/admin/thumbnail_progress 2.78ms
[96m[DEBUG] [0m2022/02/23 23:00:26 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:00:28 | 200 GET /api/admin/thumbnail_progress 3.63ms
[96m[DEBUG] [0m2022/02/23 23:00:33 | 200 GET /api/admin/thumbnail_progress 3.78ms
[96m[DEBUG] [0m2022/02/23 23:00:37 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:00:38 | 200 GET /api/admin/thumbnail_progress 2.39ms
[96m[DEBUG] [0m2022/02/23 23:00:43 | 200 GET /api/admin/thumbnail_progress 3.44ms
[96m[DEBUG] [0m2022/02/23 23:00:47 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:00:48 | 200 GET /api/admin/thumbnail_progress 3.28ms
[96m[DEBUG] [0m2022/02/23 23:00:53 | 200 GET /api/admin/thumbnail_progress 3.05ms
[96m[DEBUG] [0m2022/02/23 23:00:57 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:00:58 | 200 GET /api/admin/thumbnail_progress 3.32ms
[96m[DEBUG] [0m2022/02/23 23:01:03 | 200 GET /api/admin/thumbnail_progress 2.45ms
[96m[DEBUG] [0m2022/02/23 23:01:07 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:01:08 | 200 GET /api/admin/thumbnail_progress 3.7ms
[96m[DEBUG] [0m2022/02/23 23:01:13 | 200 GET /api/admin/thumbnail_progress 2.1ms
[96m[DEBUG] [0m2022/02/23 23:01:17 | Thumbnail generation progress: 4.7%
[96m[DEBUG] [0m2022/02/23 23:01:18 | 200 GET /api/admin/thumbnail_progress 3.07ms

**Comment by hkalexling** [comment]
Thanks for the bug report. I think a file your library is corrupted, but yeah I agree Mango should log the file path that's causing the issue. I will work on this.
