### ISSUE TITLE
[Bug Report] Error Searching Manga with MangaDex Plugin

### ISSUE THREAD

**Issue by eroc1990** [hkalexling/Mango#290]
**Describe the bug**
When searching for manga using the Mangadex plugin, the following error is received:

`Search failed. Error: Error: Missing required fields in the Manga type`

**To Reproduce**
1. Navigate to Download > Plugins
2. Select MangaDex from the dropdown
3. Search for any manga title (sans punctuation, since that also throws an error)

**Expected behavior**
A search result should be returned by the search attempt

**Environment (please complete the following information):**

**Client**
- Firefox flatpak, ver 98.0.2
- Pop_OS! 21.10

**Server**
- Unraid 6.9.2 running Docker ver 20.10.5
- Mango ver 0.26.0

**Docker (if you are running Mango in a Docker container)**
version: '2'
services:
    mango:
        image: hkalexling/mango
        container_name: ""
        environment:
            - TZ=America/New_York
            - HOST_OS=Unraid
        volumes:
            - /mnt/disk2/dockerRoot/mango/appdata
            - /mnt/disk1/dockerRoot/mango/mangas

**Additional context**
Logged in stdout as well:
[91m[ERROR] [0m2022/04/03 20:05:43 | Missing required fields in the Manga type
[91m[ERROR] [0m2022/04/03 20:05:43 | Missing required fields in the Manga type

**Comment by hkalexling** [comment]
It works fine for me. Are you using the default settings from the plugin in `info.json`? Or did you customize any value?

![DeepinScreenshot_select-area_20220404101404](https://user-images.githubusercontent.com/7845831/161463128-c0c8c10d-96c6-4ea5-b746-27d04746e2f8.png)

**Comment by eroc1990** [comment]
The values are the defaults currently in the plugins folder in your repo. Only thing I did was download the plugins with GitZip, unzipped the folder, and uploaded them to the plugins directory on the server I'm hosting it on.

**Comment by eroc1990** [comment]
No, I do see what you mean. I guess some titles aren't returning results, and it's throwing that error when nothing's found. I was able to successfully replicate the test you ran in your screenshot.

**Comment by eroc1990** [comment]
Searched the English and Romanji titles of Ijiranaide, Nagatoro-san. That caused the error above to appear.

**Comment by hkalexling** [comment]
Thanks! It's indeed a bug with the plugin and it has been fixed in https://github.com/hkalexling/mango-plugins/pull/22. Simply updating the plugin should fix it.

**Comment by eroc1990** [comment]
Seems we might not be out of the woods yet. The search works fine, but if I choose one of its resulting manga, I receive a similar error:

`Failed to list chapters. Error: Error: Missing required fields in the Chapter type`

![image](https://user-images.githubusercontent.com/13401635/161769332-f98fde4b-d30c-40cb-849a-37f7600c51c6.png)

**Comment by hkalexling** [comment]
Should be fixed by https://github.com/hkalexling/mango-plugins/pull/23 now :)

**Comment by eroc1990** [comment]
That did it!
