### ISSUE TITLE
[Feature Request] Support standalone mobile web app

### ISSUE THREAD

**Issue by alethiophile** [hkalexling/Mango#296]
**Is your feature request related to a problem? Please describe.**
It would be nice for Mango to support the standalone web app system in iOS and Android. This allows it to act like an app on its own, rather than only being accessible in a browser tab.

**Describe the solution you'd like**
This can be enabled trivially by serving [a few meta tags](https://gist.github.com/hal0gen/5852bd9db240c477f20c) in the Web page output. 

**Describe a small use-case for this feature request**
The use case is to run Mango as a standalone app rather than a browser tab.

**Additional context**
Note that this is related to, but distinct from, #185. Support for offline reading is common among standalone web apps in this general category, but not required.

**Comment by hkalexling** [comment]
We do have #262. Is that what you are looking for?

**Comment by GlassedSilver** [comment]
> We do have #262. Is that what you are looking for?

Without background workers that really just ends up being a multi-window-moded browser experience rather than something that feels self-contained and more like an app.

Yes it's not clogging up your tabs, but it's a very subpar experience and not really a web app.

**Comment by hkalexling** [comment]
@GlassedSilver Yeah I totally understand, and in fact we do have plans for an official React Native app (it's in a private repository at the moment). I was just replying to what @alethiophile said as I think we already have what they were requesting

> This can be enabled trivially by serving [a few meta tags](https://gist.github.com/hal0gen/5852bd9db240c477f20c) in the Web page output.

**Comment by hkalexling** [comment]
I am going to close the issue because 

1. The requested feature seems to exist already. If I misunderstand what you said, please let me know, and we can reopen the issue.
2. I think a dedicated React Native app will offer a better mobile experience. I would rather not go down the progressive web app rabbit hole.
