### ISSUE TITLE
Support for RSS in the reader

### ISSUE THREAD

**Issue by DisableGraphics** [hkalexling/Mango#298]
OPDS is a great protocol to use, but there's little support for it. For example, as far as I know, in Linux there are only two OPDS readers ([Thorium reader](https://github.com/edrlab/thorium-reader) and [Lucidor](http://lucidor.org/lucidor/)) and only Lucidor works with Mango (And its controls are weird). Also, most OPDS readers I've found for other platforms only support books, not comics/manga.

RSS is much more supported (A search query for "RSS reader" in my package manager yields more than 20 results) and OPDS is based on RSS. Moreover, RSS supports images, as seen in the RSS feed for [XKCD](https://xkcd.com).

**Comment by hkalexling** [comment]
Interesting idea. I've never seen RSS feeds used like this. I am not very familiar with RSS standard, but is it possible to group multiple images into a chapter? Each entry in XKCD is just a single image so it's easy to pack it into RSS (https://xkcd.com/rss.xml), but I am not sure how feasible it is for more structural data where we have multiple images in a chapter and multiple chapters in a collection, etc.

**Comment by DisableGraphics** [comment]
To be honest, I'm not really an expert on RSS too. Well... taking into consideration that XKCD uses an `<img src>` tag in the RSS feed, probably it could be the same with mango, although with more than just one tag.
Edit: I've loaded the feed into GFeeds and all the images (It seems there's not only one image in the page) have loaded correctly, so this should _probably_ be feasible

**Comment by DisableGraphics** [comment]
Screenshot for clarification
![Gfeeds](https://user-images.githubusercontent.com/48135147/165080340-de8714c7-c57e-4f9f-a796-6d59b237e0f3.png)

**Comment by hkalexling** [comment]
Hmm from the screenshot I am pretty sure your RSS reader just opens the URL in the `<link>` tag and renders the HTML like what a browser does. If that's what you are looking for why not use Mango from your browser?

**Comment by DisableGraphics** [comment]
I can't use my browser offline. I know RSS is supposed to be an on-line protocol _but_ the server is a local one, probably it _could_ work. Sorry for this late reply
