### ISSUE TITLE
Add "return to library" button at the top and bottom of every chapter.

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#3]
Having to press back isn't very elegant; having a button to return directly to the main library page, and perhaps another button to return to the manga's page, would be very nice indeed.

Thanks for all your hard work!

**Comment by hkalexling** [comment]
I agree! I think both this and #4 are great features and should be added to every page applicable. I will try to include them in the next release.

> and perhaps another button to return to the manga's page

By this do you mean a button to return to the home page? You can do this by clicking on "Home" or the Mango icon on the navigation bar. Is that what you are looking for?

Also, thanks for creating a GitHub account just to support my work. It means a lot!

**Comment by hkalexling** [comment]
Sorry, it looks like I misunderstood what you meant. If you want to go back to the manga page from the web reader, you can simply click on any page and use the "Exit Reader" button in the pop-up window.

<img width="979" alt="Screen Shot 2020-02-28 at 1 33 35 PM" src="https://user-images.githubusercontent.com/7845831/75577049-25102800-5a2f-11ea-8784-9856bb5b53ce.png">

Is this what you are looking for?

**Comment by DuraMorte** [comment]
Yes indeed! I didn't realize that box was there until I discovered it by accident.
Thank you for your hard work; my wife and I are enjoying this software immensely!

**Comment by hkalexling** [comment]
Great! Glad to know that you are happy with it! :D
