### ISSUE TITLE
[Bug Report]: ARM64v8 binary not working in arm64 device

### ISSUE THREAD

**Issue by z8512** [hkalexling/Mango#309]
**Describe the bug**

**To Reproduce**
1. Go to 'Termux'
2. Download mango-arm64v8.o binary
3. Run mango
4. Get `zsh: exec format error`

**Expected behavior**
The binary should run without any issue in arm64 device

**Environment (please complete the following information):**
 - OS: Android 11
 - Browser Firefox
 - Mango Version v0.26.2

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.
Termux app

**Comment by hkalexling** [comment]
Hey thanks for the detailed report. The `.o` file is an object file and not an executable. Running Mango on ARM devices is a bit more involved and would require docker. See https://github.com/hkalexling/Mango/wiki/Platform-Support
