### ISSUE TITLE
[Feature Request] ARM Support on Pre-built Binary or Docker.

### ISSUE THREAD

**Issue by toxikmicrowave** [hkalexling/Mango#316]
**Is your feature request related to a problem? Please describe.**
Current release (Pre-built Binary or Docker) of Mango has no support for ARM CPUs.

**Describe the solution you'd like**
Pre-built Binary or Docker Image with support for ARM CPUs.

**Describe a small use-case for this feature request**
Being able to use Mango on small ARM devices like Raspberry Pi.

**Comment by hkalexling** [comment]
Hey thanks for the feature request. Unfortunately statically linking is not yet possible with Crystal on ARM (see #131), and the prebuilt ARM docker image has already been requested here: https://github.com/hkalexling/Mango/issues/297
