### ISSUE TITLE
[Bug Report] Dockerfile fails to build from `master` and `v0.26.2` tag on Windows

### ISSUE THREAD

**Issue by tylercamp** [hkalexling/Mango#318]
**Describe the bug**
Attempting to build a docker image fails with error:

```
#13 100.8 Using sanitize (0.1.0 at e09520e)
#13 100.8 crystal build src/mango.cr --release --progress --static --error-trace
#13 101.0 In src/mango.cr:1:1
#13 101.0
#13 101.0  1 | require "./config"
#13 101.0      ^
#13 101.0 Error: while requiring "./config"
#13 101.0
#13 101.0
#13 101.0 In src/config.cr:50:58
#13 101.0
#13 101.0  50 | puts "The config file #{cfg_path} does not exist. " \
#13 101.0                                                            ^
#13 101.0 Error: unknown token: '\r'
make: *** [Makefile:18: static] Error 1
```

**To Reproduce**
Clone the repo and run `docker build -t XYZ .`

**Environment (please complete the following information):**
 - OS: *Windows 11, using Docker with WSL 2 backend*
 - Mango Version: *`master`, `v0.26.2`*

**Docker (if you are running Mango in a Docker container)**
- I've copied the `env.example` file and renamed to `.env`, no modifications

**Additional context**
I'm attempting to build the image myself so I can add an `EXPOSE 9000` line to the Dockerfile; explicit EXPOSE is needed in the docker image for Traefik which auto-detects ports for containers and exposes them behind HTTPS.

I've not tried older tags.

**Comment by hkalexling** [comment]
Windows line breaks strike again :) Can you give https://github.com/hkalexling/Mango/issues/306#issuecomment-1147999115 a try?

**Comment by tylercamp** [comment]
@hkalexling Thank you for that note and quick response, I've instead cloned and built the repo using Ubuntu on Windows (instead of via Windows terminal) and I was able to build the image without issue
