### ISSUE TITLE
Log location?

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#32]
I apologize if this is a stupid question, but does Mango write a log file, and if so, where is it?

I've crawled through /var/log, but I can't seem to locate it anywhere.

**Comment by hkalexling** [comment]
Mango always logs to stdout, but you can always redirect the outputs to a file using

```
./mango >> /path/to/mango.log 2>&1
```

If you are running Mango as a systemd service, you can follow the answers under [this](https://stackoverflow.com/questions/37585758/) SO question.

**Comment by DuraMorte** [comment]
Fair enough! I'll handle it. Thanks!
