### ISSUE TITLE
[Feature Request] Add an option for the specific port

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#38]
**Is your feature request related to a problem? Please describe.**
A bunch of apps run on port 9000 and it would be nice to be able to specify which port to run the application on.

**Describe the solution you'd like**
An option in the config.yml for the port integer to run the webserver on

**Additional context**
n/a

**Comment by hkalexling** [comment]
Perhaps I misunderstood what you meant, but the config file does have a port field. See https://github.com/hkalexling/Mango#config

**Comment by flying-sausages** [comment]
@hkalexling no you understood right. I straight up missed it like 3 times my bad. hahaha sorry!
