### ISSUE TITLE
[Feature Request] Auto-download new episodes

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#39]
**Is your feature request related to a problem? Please describe.**
I would love to have a way to pre-download chapters so that I can read them whenever I want. I am coming from the perspective of a Sonarr user, which scans in the background every n minutes for new episodes of shows that are being "monitored" or in Mangadex context "followed".

**Describe the solution you'd like**
One of the following:
- Auto-download from the RSS of titles that are followed
- Mark shows as being followed and auto-download by scanning magadex for new chapters in an interval and retrieve the follwed titles either from:
  - Mangadex user through allowing access with credentials
  - Marking titles as followed in the interface manually

**Additional context**
I think the second option would be preferrable as you can then use the filter to specify groups, and/or make sure that only one copy is downloaded. You could also only keep the copy that is of the highest resolution.

My use-case comes from wanting to auto-push new chapters to my Kobo reader which has dropbox support. This could also be used for anyone else pushing the content to their readers through ODPS, etc.

**Comment by hkalexling** [comment]
Thanks for reaching out! The feature is already proposed in #24, so I am closing this issue.

Yes I prefer the second option as well and I am working on it. It's not a small feature, so it might take some time. You can subscribe to #24 to get updated.

**Comment by flying-sausages** [comment]
I need to put down the vodka sprite... Thanks again

**Comment by hkalexling** [comment]
Haha, no problem :D
