### ISSUE TITLE
Add "Sort" dropdown to library view.

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#4]
It's annoying to be scrolling through the library and it (seemingly) has no rhyme or reason to it's order. A simple dropdown menu with a "#-Z", "Z-#", "Date Added (Recent First)" would be perfect.

Thanks!

**Comment by hkalexling** [comment]
See #3, this should be added in the next release.

**Comment by hkalexling** [comment]
This is added in [v0.1.2](https://github.com/hkalexling/Mango/releases/tag/v0.1.2). Thanks for the feature request!
