### ISSUE TITLE
[Feature Request] Prevent navbar from moving upon reload

### ISSUE THREAD

**Issue by jakoblover** [hkalexling/Mango#40]
**Is your feature request related to a problem? Please describe.**
When a page is reloaded in Mango, the navbar keeps jumping around mostly from the icon in the top left being reloaded.

**Describe the solution you'd like**
Prevent the navbar from jumping around when reloading

**Comment by hkalexling** [comment]
Thanks for reaching out. 

May I know which browser you are using? If possible, could you please send me a screen recording (either a video or a gif file) showing the issue? I tested it on all major browsers and the navbar loads fine without any jumping (even when the network is throttled). Normally your browser should cache the icon so I am not sure what went wrong. It would be helpful if you could try it on another browser to isolate the problem.

**Comment by jakoblover** [comment]
It does not work with the latest Chrome. It did however work with Edge.

![c4abd0c9a94e6f8dd314610d134ca2d5](https://user-images.githubusercontent.com/14160441/82680755-05168c00-9c4d-11ea-8738-77ac7f758ff7.gif)

**Comment by hkalexling** [comment]
I see. Somehow it doesn't happen in my Chrome, but this should be easy to fix by explicitly setting the icon size. I will fix it in the next release.

Thanks for the heads up!

**Comment by hkalexling** [comment]
Hi, this should be fixed in [v0.4.0](https://github.com/hkalexling/Mango/releases/tag/v0.4.0). Thanks again for reporting!

Feel free to reopen if you still encounter the issue.
