### ISSUE TITLE
[Feature Request] Direct download button

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#45]
**Is your feature request related to a problem? Please describe.**
I'd like to download the cbz file when I am browsing the web UI from my phone/iPad

**Describe the solution you'd like**
A button that would serve up a direct download link for the CBZ archive in question

**Comment by hkalexling** [comment]
Added in [v0.7.0](https://github.com/hkalexling/Mango/releases/tag/v0.7.0). Thanks for the feature request!
