### ISSUE TITLE
[Feature Request] BaseURL support

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#46]
**Is your feature request related to a problem? Please describe.**
I would like to run mango behind a reverse proxy with a base url, i.e. `<domain.tld>/mango` instead of `<domain.tld>:9000`

**Describe the solution you'd like**
A line in the config.yml to set the `baseurl`

**Additional context**
Would be nice to have this included here too https://github.com/hkalexling/Mango/pull/43#discussion_r429515713.
I'm struggling to do this right now with my nginx knwoledge

**Comment by hkalexling** [comment]
I think [this SO question](https://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite) is what you are looking for? I use Apache so I couldn't test it for you.

**Comment by flying-sausages** [comment]
Been working on this this whole time and none of these answers do it for me. When I try access `<domain.tld>/mango` I get sent straight to `<domain.tld>/login` without `mango` in there. I'll update this if I find a good way to do this rewrite.

But ideally, there would be a similar option to this for example https://github.com/Flood-UI/flood/blob/master/config.template.js#L15

**Comment by hkalexling** [comment]
Ah, you are right, I wasn't thinking clearly (missed my morning coffee). This should indeed be done in the application itself. 

I saw your PR draft for the swizzin repo. I will prioritize this feature request so you can work on that soon.

**Comment by flying-sausages** [comment]
No stress! I appreciate the thought though :)

**Comment by hkalexling** [comment]
Hi, base URL is now configurable in [v0.4.0](https://github.com/hkalexling/Mango/releases/tag/v0.4.0). Please check the [Wiki](https://github.com/hkalexling/Mango/wiki/Additional-Configurations#base-url) for details.

I am closing this issue, but feel free to reopen.

**Comment by flying-sausages** [comment]
Heya, that was fast! I'm getting too many redirects right now however... https://termbin.com/pv7f

Did I do something wrong?

This is the config I am using. I'm getting the same when I use `/mango` and `/mango/` in there
https://github.com/liaralabs/swizzin/pull/336/files#diff-92341616a03987b8325d9b8f89855792R38-R54

**Comment by flying-sausages** [comment]
Same when accessing `localhost/mango` with the nginx reverse proxy confed up https://termbin.com/51wrk

**Comment by flying-sausages** [comment]
also fwiw Issue author cannot re-open issue if maintainer closed them ;) https://github.com/isaacs/github/issues/583

**Comment by hkalexling** [comment]
I think it's because you missed the trailing slash in the Nginx config https://github.com/liaralabs/swizzin/pull/336/files#diff-3379b784c846d1072ebf4359a2074ba2R6

It should be `proxy_pass http://localhost:9003/;` instead.

Oops, I didn't know you cannot reopen. Thanks for letting me know! I will reopen this issue if the problem still persists after adding the slash.

**Comment by flying-sausages** [comment]
Yeah that's what's up. Cheers man, really appreciated!
