### ISSUE TITLE
[Feature Request] Download from KissManga

### ISSUE THREAD

**Issue by Nonobis** [hkalexling/Mango#47]
Is your feature request related to a problem? Please describe.
Could you add KissManga (https://kissmanga.org/) as a downlaod provider ?

Describe the solution you'd like
Support for other provider, maybe a documentation for creating a provider ?

Thanks

**Comment by hkalexling** [comment]
Thanks for reaching out!

We do have a plan for a plugin system to integrate other manga sites (see https://github.com/hkalexling/Mango/projects/3#card-33959584), but it involves a lot of work so you might have to wait :/

For now, I would suggest using an external downloader and manually moving the downloaded cbz/zip files to your Mango library.

**Comment by hkalexling** [comment]
I have created issue #48 dedicated to the plugin system. You can subscribe to that issue to get updated.

Closing this.

**Comment by hkalexling** [comment]
Plugin support in now available in [v0.9.0](https://github.com/hkalexling/Mango/releases/tag/v0.9.0). Please consider contributing a KissManga plugin to https://github.com/hkalexling/mango-plugins!
