### ISSUE TITLE
[Bug Report] Filtering results not working as expected

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#51]
**Describe the bug**
When adding a group to a filter that has obvious results without the filter, they do not show up

**To Reproduce**
1. Please see screenshots

**Expected behavior**
The 967 from the Little miss etc group

**Environment (please complete the following information):**
 - OS: U20.04
 - Browser FF68ESR
 - Mango Version 0.4.0

**Additional context**

![image](https://user-images.githubusercontent.com/23618693/83467859-062c9200-a473-11ea-89f3-6223a4416dbc.png)

and then using a group filter
![image](https://user-images.githubusercontent.com/23618693/83467903-252b2400-a473-11ea-8e4d-c5db416f6c63.png)

**Comment by hkalexling** [comment]
Thanks for the heads up! This is fixed in the dev branch. I will make a new release soon.

**Comment by hkalexling** [comment]
Fixed in [v0.5.0](https://github.com/hkalexling/Mango/releases/tag/v0.5.0).
