### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Sumitkrsaw** [hkalexling/Mango#58]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser [e.g. chrome, safari, if applicable]
 - Mango Version [e.g. v0.1.0]

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.

**Comment by hkalexling** [comment]
Bot? Closing and reported...

**Comment by iyome1** [comment]
hi
