### ISSUE TITLE
Manga with apostrophe in title do not open.

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#6]
Any manga in my collection that has an apostrophe in the name will not open.

1. Add an apostrophe to any title (or transfer a manga with an apostrophe in the title into the library directory).
2. Rescan library.
3. Attempt to open the affected title.
4. No response from page. (Preliminary window never opens.)

Manga that do not have ' in the title are unaffected. Brackets ( [ ] ), dashes ( - ), exclamation points (!), and parenthesis have no effect. Only apostrophies, so far. Will update report if more are found.

**Comment by hkalexling** [comment]
Good catch! I have identified the issue in code, and will probably make a bug fix release later today.

**Comment by hkalexling** [comment]
This issue is fixed in [v0.1.1](https://github.com/hkalexling/Mango/releases/tag/v0.1.1). Thanks for the bug report!
