### ISSUE TITLE
Slashes in chapter name prevents chapter from downloading

### ISSUE THREAD

**Issue by outnos** [hkalexling/Mango#62]
**Describe the bug**
If the chapter contains a slash Mango attempts to open the file in a subfolder, which dosent exist and the download freezes.
[ERROR]   2020/06/08 20:13:44 | Error opening file with mode 'w': '/mnt/extrafiles/mango_lib/library/Dogeza De Tanondemita/Ch.40 Coming of Age/Adult's Day.cbz': No such file or directory

**To Reproduce**
1. Download series 30590 chapter 40

**Expected behavior**
I would expect the slashes to be filtered out, as to prevent such issues, same with ".."

**Environment (please complete the following information):**
 - OS: Manjaro Linux 20.0.3 - Lysia
 - Browser: Firefox 77.0.1
 - Mango Version 0.5.2

**Comment by hkalexling** [comment]
Thanks for the bug report! The issue is fixed in the development branch by replacing illegal characters with `_`. I will make a new release soon.

**Comment by outnos** [comment]
👍
