### ISSUE TITLE
Download server issues with new MangaDex@Home

### ISSUE THREAD

**Issue by outnos** [hkalexling/Mango#63]
**Describe the bug**
Chapter in question, Series 18734 chapter 29 (185017).

With some chapters, if you attempt to get information from the mangadex api like so "https://mangadex.org/api/chapter/185017" you will get the general json information page with some server url like "s2.mangadex".

But if you do it without an user-agent, you receive another server url like this one "https:\/\/tje23x26yczcr.tceq6s3bnjcyj.mangadex.network:443\/data\/", which Mango fails to connect to.
I actually don't know if this is a Mangadex or Mango issue, since i cannot seem to get the image from that url either.
Firefox just says "The image 'X' cannot be displayed as it contains errors."

> [WARNING] 2020/06/09 12:07:51 | Failed to download page https://mactzbskc0zxm.ztxvgq2d6yc0e.mangadex.network:5535/data/7251260e9126852d439081eb6f7bc035/x1.png. Retrying... Remaining retries: 3
> [ERROR]   2020/06/09 12:07:58 | SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

**To Reproduce**
1. Download chapter 29 of series 18734

**Expected behavior**
I would expect it to successfully download

**Environment (please complete the following information):**
 - OS: Manjaro Linux 20.0.3
 - Browser: Firefox 77.0.1
 - Mango Version: 0.5.2

**Comment by hkalexling** [comment]
Yeah, I am starting to get the same error today. Mango does use a user-agent when communicating with the API (see [here](https://github.com/hkalexling/Mango/blob/bec257c99fcb35b9fce844d93eae7e1f213ba1db/src/mangadex/api.cr#L152)). In my experience this issue goes away after some time, and I am not sure what triggers it. I will investigate and see if there's anything we can do. I don't like making Mango look like a real browser by setting fake values in the user-agent, so that would be the last resort.

**Comment by hkalexling** [comment]
It looks like MangaDex only returns the real server URL when the user is logged in. Try accessing https://mangadex.org/api/chapter/185017 in a private window and you will get the wrong URL. Unfortunately, Mango does not support MangaDex login. I will have to implement this feature if the problem persists.

**Comment by outnos** [comment]
It seems this is their new MangaDex@Home initiative, and is a server sided issue. 
But we should still refresh the chapter index as to get a new "server" if the current one is unresponsive.

**Comment by hkalexling** [comment]
Yeah, I noticed that too, but the solution sounds a bit hacky. I will focus on this and hopefully we can get the login functinality in the next version!

**Comment by outnos** [comment]
I dont think login in fixes this, as i tried getting "One Punch Man" chapter one while logged in, and it gave me a @Home address, but i did figure out how to login (with python not crystal though).
```
import requests

url = "https://mangadex.org/ajax/actions.ajax.php?function=login&nojs=1"
data = {
	"login_username": "USERNAME", 
	"login_password": "PASSWORD",
	"two_factor": "",
	"remember_me": "1",
}

req = requests.post(url, data)
print(req.headers)
print(req.headers["Set-Cookie"])
```
Where the response header contains a Set-Cookie with a "mangadex_session=X;" line, which is the session id.
This might be useful for the on-by-default data compression, but not for fixing @Home.

**Comment by hkalexling** [comment]
> I dont think login in fixes this, as i tried getting "One Punch Man" chapter one while logged in, and it gave me a @Home address

I just tested it and https://mangadex.org/api/chapter/67377 always returns the real server URL when logged in. Are you sure you are sending the correct session ID in the header when making the request?

Thanks for investigating the login API. I will work on this in the coming weekend.

**Comment by outnos** [comment]
I just logged into Mangadex, went to chapter 1 and copied the image source, and it originated from @Home. So im pretty sure its just a regional difference, and logging in does not ensure that its consistently from the original source.

**Comment by hkalexling** [comment]
@flying-sausages Thanks! Here's what they said

> Long story short, this bug has been fixed, but that node owner hasn't updated his node
> try another node

So it's a temporary issue on their side. Closing.
