### ISSUE TITLE
[Bug Report] Login redirects you to favicon.ico in v0.6.0

### ISSUE THREAD

**Issue by jaredlt** [hkalexling/Mango#64]
## Steps to reproduce

- Install Mango v0.6.0
- Login

## What you expected to see

- Taken to Mango root

## What you saw instead

- Redirected to `http://localhost:9000/favicon.ico` (when I manually visited `http://localhost:9000/` it worked fine)
- I tried logging out and logging back in again and this time was redirected to `http://localhost:9000/js/fontawesome.min.js` and after logging out again was redirected to `http://localhost:9000/js/solid.min.js`

**Comment by hkalexling** [comment]
Fixed in [v0.6.1](https://github.com/hkalexling/Mango/releases/tag/v0.6.1). Thanks for the quick bug report!
