### ISSUE TITLE
"Package libarchive was not found in the pkg-config search path" when building from source

### ISSUE THREAD

**Issue by jaredlt** [hkalexling/Mango#65]
I've just tried to build from source since you introduced libarchive for rar support and am getting the following error:

`Package libarchive was not found in the pkg-config search path`

I have `libarchive-tools` and `libarchive13` installed via apt (Ubuntu via WSL).

How did you install libarchive? And do you have any suggestions for me? :)

**Comment by hkalexling** [comment]
For development, you usually want to install the dev libraries, which include the development headers. See https://stackoverflow.com/q/1157192

In this particular case you need [`libarchive-dev`](https://packages.ubuntu.com/search?keywords=libarchive-dev).

**Comment by jaredlt** [comment]
Seems so obvious now that you've explained it 🤦‍♂️ Thank you!
