### ISSUE TITLE
[Feature Request] Add webp image support

### ISSUE THREAD

**Issue by outnos** [hkalexling/Mango#69]
**Is your feature request related to a problem? Please describe.**
Currently only PNG and JPEG is supported, but new formats like WEBP gives you impressive space saving results when used on manga images, so i would like to see added support for it.
On my personal library i found over 50% less space was used.
I found even more impressive results with HEIC, but no browser supports it, so we'd need to supply a client sided converter for it, which is cumbersome.

**Comment by hkalexling** [comment]
Supporting webp is a good idea. I will include this in the next version.

For HEIC (and other currently unsupported filetypes), we could use something like [`libvips`](https://github.com/libvips/libvips) to convert the images to jpeg on the fly before serving them. I don't think HEIC support should be prioritized at this stage as it's rare to find archives containing HEIC images, but PRs are always welcome.

**Comment by outnos** [comment]
I see commit dc084aff7c25ff84569941e49c1188fd5cdb4fbe where you added webp support and am closing the issue.

**Comment by hkalexling** [comment]
This feature is now available in [v0.7.0](https://github.com/hkalexling/Mango/releases/tag/v0.7.0). Thanks for the request!
