### ISSUE TITLE
[Feature Request] Add colours to Status on Download Manager in Dark Mode

### ISSUE THREAD

**Issue by cglatot** [hkalexling/Mango#70]
**Is your feature request related to a problem? Please describe.**
Dark mode is great, and I love it - however, removing the colours from the Download Manager is annoying. Please add the colours back, or use alternative colours.

**Describe the solution you'd like**
Have "Completed", "Downloading", and "Pending" be different colours in dark mode.

**Describe a small use-case for this feature request**
It makes it much easier to see your queue's status at a glance.

**Other notes**
"Downloading" should also be a different colour than "Pending" - so that they can stand out more. This should be on both Dark Mode and Light Mode.

**Comment by hkalexling** [comment]
Good idea 👍 Will try to include this in the next release.

**Comment by hkalexling** [comment]
This feature is now available in [v0.7.0](https://github.com/hkalexling/Mango/releases/tag/v0.7.0). Thanks for the request!

<img width="968" alt="Screenshot 2020-06-20 at 10 04 36 PM" src="https://user-images.githubusercontent.com/7845831/85203752-5e540700-b342-11ea-8f56-33fad6933315.png">
