### ISSUE TITLE
[Feature Request] next entry button should start at beginning of next chapter/entry

### ISSUE THREAD

**Issue by Docteh** [hkalexling/Mango#71]
**Describe the bug**
"Next entry" doesn't consistently load the beginning of the next chapter

**To Reproduce**
1. Read the latest chapter of something, realize I've forgotten whats going on.
2. Read previous chapters, using "next entry" to move forward.
3. 

**Expected behavior**
I'd like to reread things without having to watch out for the reader to be continuing from where i left off.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: chrome
 - Mango Version 0.6? maybe? is this indicated anywhere? 😃 

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.

**Additional context**
Mango was skipping inwards earlier on chapters that I've read 100% of, but its not consistent. But if I've partially read a chapter, the next entry button skips to that point. 

I've also noticed there doesn't seem to be an easy way to tell which file I'm in

Is the mango version listed anywhere in the web interface?

**Comment by hkalexling** [comment]
This is the expected behavior. No matter how you start a chapter (clicking "next entry" or directly opening it from the list), Mango remembers where you left off and starts from there. We take inspiration from [Plex](https://www.plex.tv/) for our UX design, and in Plex the web player starts from your last watched time when jumped from the previous episode. 

> I've also noticed there doesn't seem to be an easy way to tell which file I'm in

Good point 👍 Perhaps we can add a line to display the chapter title and file path in the pop-up windows in reader.

> Is the mango version listed anywhere in the web interface?

Currently, it's only available from the command line by running `mango --version`, but I agree showing it on the admin page would improve the user experience. I will include this in the next release.

**Comment by Docteh** [comment]
I had some issues repeating my issue so I spent some time figuring it out,  When the reader is told to "Start from 100%" it starts from 10 pages left, and the series I'm re-reading has some chapters above 10 pages, and some below. Yay split chapters.


When I "next entry" in to a chapter that I've read 100%, I'd like to start at page 1. Not too picky about partially read chapters, I can figure those out.

**Comment by hkalexling** [comment]
> it starts from 10 pages left

When starting a chapter, Mango "rewinds" the progress a bit so you can recall what was going on.

>  and the series I'm re-reading has some chapters above 10 pages, and some below. Yay split chapters.

Sorry, I don't understand what you meant. Why is that a problem?

> When I "next entry" in to a chapter that I've read 100%, I'd like to start at page 1

This makes more sense than starting all chapters from page one. We can probably have this in the next release.

Just to be sure, are you aware that you can quickly switch to another page using dropdown selection from the reader popup window? You can open the popup window by clicking on any page in the reader.

<img width="734" alt="Screenshot 2020-06-15 at 4 18 43 PM" src="https://user-images.githubusercontent.com/7845831/84634130-f48fc380-af23-11ea-8717-ce25f8ff92da.png">

**Comment by Docteh** [comment]
>> and the series I'm re-reading has some chapters above 10 pages, and some below. Yay split chapters.

> Sorry, I don't understand what you meant. Why is that a problem?

Its just a background detail to explain why the problem was not very clear. 

>>When I "next entry" in to a chapter that I've read 100%, I'd like to start at page 1

>This makes more sense than starting all chapters from page one. We can probably have this in the next release.

Thanks!

**Comment by hkalexling** [comment]
The requested changes/features are now available in [v0.7.0](https://github.com/hkalexling/Mango/releases/tag/v0.7.0). Thanks for the request!
