### ISSUE TITLE
[Question] Automatization metadata

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#72]
Hi, I don't understand one thing, is there a system that downloads the metadata of the manga? Example I add The rising of the shield hero vol 1 and 2. <Library / Tate no Yuusha / Volume 1 / Cap1.zip ...> are searched (maybe on comicsvine via Key) manga name and cover + plot year etc. issue cover etc. If this system is not present, is it possible that it will be added in the future?
Sorry for my english.

**Comment by hkalexling** [comment]
Thanks for reaching out!

Mango doesn't search for metadata at this moment. We plan to support post-processing scripts (#52), and what you described should be possible with a script/plugin when the feature is available.

I am not familiar with comicsvine. Do they have public APIs for metadata searching? Alternatively, do you know any other websites that can be used to fetch metadata with APIs?

**Comment by zFerry98** [comment]
Tenma is a similar software, use Comicsvine for metadata scrap. https://github.com/Tenma-Server/Tenma. 
I don't know of any other sites that allow you to download metadata officially via Key. I know there is the first method used by software like Tenma and plex (TheTVDB, TheMovieDB) or by creating a script / plugin that reads the web page. Type for plex there are scrappers that do the research using the series title such as querry, the specific page where there are metadata is analyzed (html it seems to me) and "steals" the data by entering them in the various fields. Example a scraper that searches on thetvdb looking for Dragon Ball Super, the dragon ball super page is displayed and from there reading html or whatever it is takes the data. Obviously the second method would be the one that the community adds via plugins / scripts while the first is easier because it interfaces with the official and documented bees the minimum. Sorry for English.

**Comment by zFerry98** [comment]
Rewrite Up

**Comment by hkalexling** [comment]
Thanks for providing the additional information. Yes, I think a metadata scraper is needed before v1.0, but it's not very important at this moment, so I will focus on other features first. Hope you understand!

As for the actual implementation, I prefer the ComicVine API approach. I don't have the desire nor the time to create a platform like TVDB for manga. If you or anyone else is interested in building this, I will be happy to integrate it with Mango.
