### ISSUE TITLE
[Bug Report] All manga titles reduces to "..."

### ISSUE THREAD

**Issue by cglatot** [hkalexling/Mango#73]
**Describe the bug**
All manga titles have been reduced to "..."

**To Reproduce**
On Home and Library screens, the titles of manga are all displayed as "..."

**Expected behavior**
Display the titles

**Environment (please complete the following information):**
 - Chrome OS (latest) on Chrome Browser v83
 - Also Android Chrome

![image](https://user-images.githubusercontent.com/10439257/85212478-0e2d7280-b34b-11ea-9c33-2f205bfee2dd.png)

**Comment by cglatot** [comment]
Also all chapter titles are reduced to "..."
![image](https://user-images.githubusercontent.com/10439257/85212487-3cab4d80-b34b-11ea-891d-9e0d959ed69b.png)

**Comment by hkalexling** [comment]
The same issue has been reported a few times. From #26, clearing the browser cache and storage seems to do the trick. Could you please try that and see if it helps? You can find the detailed instructions here https://github.com/hkalexling/Mango/issues/34#issuecomment-625712194

**Comment by cglatot** [comment]
Ah ha, that did indeed resolve it! Strange one!

Thanks for the timely response!
