### ISSUE TITLE
[Bug Report] Dockerfile make Failed

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#74]
**Describe the bug**
It's like someting wrong with code make the build failed

**To Reproduce**
Get source code and build with dockerfile

**Environment (please complete the following information):**
 - Mango Version v0.7.1

**Docker (if you are running Mango in a Docker container)**
- The orignal file

**Additional context**
![Snipaste_2020-06-21_16-26-09](https://user-images.githubusercontent.com/44677306/85220181-12ee3700-b3dc-11ea-914d-163ee1e5094a.png)

**Comment by hkalexling** [comment]
I couldn't reproduce this, and [this](https://github.com/hkalexling/Mango/runs/791076355) GitHub Action built the docker image successfully, so I guess it's due to some misconfigurations on your side.

**Comment by WROIATE** [comment]
But I don't change any config and code with it ( ´_ゝ｀)

**Comment by WROIATE** [comment]
I got what I do wrong...it's the CR/LF difference on windows and unix...

**Comment by hkalexling** [comment]
Glad that you figured it out! Did you clone the repo in Windows and attempt to build it in Unix? Would be great if you could document what you did in more details so it might help future users.

**Comment by WROIATE** [comment]
Sure, the main problem is I clone the repo on Windows and upload it to my Nas.

**Comment by whiskywaffel** [comment]
Hey, sorry to open up this again, but I get the same message.
I cloned the repo in Windows and am trying to build it with docker-compose on the same machine.

Is there a way to build it somehow?

```
...
#11 94.09 Using exception_page (0.1.4)
#11 94.09 Using kemal (0.27.0)
#11 94.09 Using koa (0.7.0)
#11 94.09 Using tallboy (0.9.3)
#11 94.09 Using mg (0.3.0 at a19417a)
#11 94.09 Using myhtml (1.5.1)
#11 94.09 Using mangadex (0.8.0 at 24e6fb5)
#11 94.09 crystal build src/mango.cr --release --progress --static --error-trace
#11 94.23 In src/mango.cr:1:1
#11 94.23
#11 94.23  1 | require "./config"
#11 94.23      ^
#11 94.23 Error: while requiring "./config"
#11 94.23
#11 94.23
#11 94.23 In src/config.cr:61:58
#11 94.23
#11 94.23  61 | puts "The config file #{cfg_path} does not exist. " \
#11 94.23                                                            ^
#11 94.23 Error: unknown token: '\r'
make: *** [Makefile:18: static] Error 1
#11 ERROR: executor failed running [/bin/sh -c make static || make static]: exit code: 2
------
 > [builder 5/5] RUN make static || make static:
------
executor failed running [/bin/sh -c make static || make static]: exit code: 2
Service 'mango' failed to build : Build failed
```

**Comment by whiskywaffel** [comment]
The workaround I found is not cloning, instead I downloaded the Zip and had to convert the docker-compose.yml and .env since they are Windows-Files
