### ISSUE TITLE
[Feature Request] Batch mark chapters as read / unread

### ISSUE THREAD

**Issue by cglatot** [hkalexling/Mango#75]
**Describe the solution you'd like**
Currently we can mark only a single chapter at a time as read, or an entire manga-worth of chapters. I would like to see a middle ground where we could batch mark many chapters as read (and similar for unread).

**Describe a small use-case for this feature request**
Often I read manga after having watched the anime. I don't want to re-read the chapters I've watched, so want to pick up where the anime left off. Currently marking each single chapter as read takes a LONG time, so would like to be able to do it en masse.

**Additional context**
There are a few ways I can see to do this (though I would be happy with any implementation of this feature):
1. Include checkboxes of some sort on each chapter so we can select the chapters we want to mark as read / unread/ Then have "Mark selected as Read" and "Mark selected as Unread" buttons at the top / bottom of the page.

2. Include fields at the top to mark X number of chapters as read / unread.

3. Make it so that the entire page doesn't reload every time you mark something as read / unread [Ideally this will be implemented as well. You should be able to update the reading progress UI without having to reload the entire page again]

**Comment by hkalexling** [comment]
I like the idea! It's not a small feature so it might take a while :-)

**Comment by hkalexling** [comment]
Added in [v0.10.0](https://github.com/hkalexling/Mango/releases/tag/v0.10.0). Thanks for the request!
