### ISSUE TITLE
[Feature Request] Keep sort mode setting with user

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#76]
**Is your feature request related to a problem? Please describe.**
Every time I want to use "date" sort mode, I have to change the option over and over again, It's not a graceful way for somebody don't want to use default mode "auto"

**Describe the solution you'd like**
Keep the Manga Sort Setting status, or add it in the Admin user setting.

**Describe a small use-case for this feature request**
Most people use a sort mode which they like with long time. If sometime I want use other mode, I could change it just once

**Comment by hkalexling** [comment]
Added in [v0.7.3](https://github.com/hkalexling/Mango/releases/tag/v0.7.3). Thanks for the feature request!
