### ISSUE TITLE
[Enhancement] Arm support

### ISSUE THREAD

**Issue by mahenkpatel** [hkalexling/Mango#78]
It would be great it we could get ARM support. This will make it possible to run in on Raspberry pi, which in turn will exponentially increase this application's reach.

**Comment by hkalexling** [comment]
This feature has been requested in #25, but Mango is having some problems to run on ARM (tested on arm32v7). I am not sure if it's due to the Crystal language or the `libsqlite3` library we are using.

I will keep this issue open and come back to it later.

**Comment by hkalexling** [comment]
ARM support has been added in [v0.11.0](https://github.com/hkalexling/Mango/releases/tag/v0.11.0). There's no pre-built binary yet, and you will have to run it in a Docker container. Please see the [wiki page](https://github.com/hkalexling/Mango/wiki/Platform-Support) for more details.
