### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#8]
I read a lot at night whilst laying in bed, and the white-on-white of the main page is blinding in the pitch dark.

A "dark mode" option would be wonderful. Swapping black text to white, white text to black, and leaving grey text grey would suffice, I think.

I realize that this may be a long time coming, and I'm fine with that. I just think it would be a nice addition. :)

**Comment by hkalexling** [comment]
Great idea! I think it won't be hard to implement. I will try to include this in the next release.

**Comment by hkalexling** [comment]
This is added in [v0.2.0](https://github.com/hkalexling/Mango/releases/tag/v0.2.0). Thanks for the feature request!
