### ISSUE TITLE
Cant Start Mango On System startup

### ISSUE THREAD

**Issue by BotWade** [hkalexling/Mango#80]
**Describe the bug**
I have a server and when i turn it on everything automatically starts (Jellyfin/WebServer/Samba/etc..), i also want to add mango but when following the tutorial instead of adding the service to user i added to system.
If i tried to restart my server or just try to start mango it gives a error `Missing ENV key: "HOME" `

**To Reproduce**
1. Follow the wiki tutorial on Systemd Service
2. instead of creating the service on the user create on the system
3. Mango fails to start

**Expected behavior**
Mango Starts

**Environment (please complete the following information):**
 - Server OS: Ubuntu 20
 - OS: Arch
 - Browser Brave
 - Mango Version v0.7.1

**Workaround**
When editing mango.service in the [Service] part add the following line
`Environment="HOME=/home/userName"`

**Comment by hkalexling** [comment]
It's not a bug with Mango. Mango uses the `$HOME` environment variable, which is set at user login. It was not yet set when the system service started, and that's why you got the error. I guess you could add `User=userName` to the service file to workaround this.
