### ISSUE TITLE
[Bug Report] Continue Reading on Home showing incorrect entries based on progress: 0 entries in info.json (v0.7.2)

### ISSUE THREAD

**Issue by jaredlt** [hkalexling/Mango#83]
**Describe the bug**

Continue Reading section on Home page shows incorrect entries if you have manually marked an entry as unread.

**To Reproduce**

- For a title you have not started (have not read any entries)
- Mark an entry as read
- Mark that same entry as unread

**Expected behavior**

Title should not show in Continue Reading section on Home page.

**Comment by hkalexling** [comment]
Ah you are right! [Here](https://github.com/hkalexling/Mango/blob/466aee62fe4288d1797e2ee94dde73568abf036d/src/library.cr#L459-L464) we only check whether the progress field exists. We should only return it if the progress value is not zero. I will fix this in the next release. Thanks for the heads up!

**Comment by hkalexling** [comment]
Fixed in [v0.7.3](https://github.com/hkalexling/Mango/releases/tag/v0.7.3). Thanks for reporting!
