### ISSUE TITLE
[Feature Request] Include Manga Name with Link on the "Continue Reading" cards

### ISSUE THREAD

**Issue by cglatot** [hkalexling/Mango#84]
**Is your feature request related to a problem? Please describe.**
Currently on the Home page, under Continue Reading, the cards only display the title of the chapter.

**Describe the solution you'd like**
I'd like to see the Manga name underneath the Chapter Name.

**Describe a small use-case for this feature request**
So you know what the manga actually is, as the chapter names and art are not always descriptive

**Comment by hkalexling** [comment]
Are you aware that after clicking on a chapter card, there's a link to the manga page in the pop-up modal? See https://github.com/hkalexling/Mango/issues/37#issuecomment-632118645

**Comment by cglatot** [comment]
Good point - completely forgot about that when writing the request. Updated the request to fix wording. I still think there is merit in having the Manga name underneath the chapter name so you can see at a glance which entry is which manga without having to click on it first.

**Comment by jaredlt** [comment]
I tend to agree. In addition to the problem @cglatot points out (entry title may be ambiguous eg. `Ch. 7`) we should also consider that sometimes the cover image may be ambiguous too (eg. Some release groups put their 'advertising' page first which isn't always clear what it represents). If we can, we should assume the worst and design the interface to still be usable with all possible issues present.

I mocked the below up some time ago when toying with the original Home concept. It borrows heavily from [Plex](https://www.plex.tv/) regarding the UX which I think they do well. This redesign is a bit more extreme in that it does more than just introduce the title. It removes the boxes, makes the font smaller and has it sit flush to the sides (so longer titles fit more characters). If we wanted something a little closer to the existing design, I've mocked up a quick version in the second image, below.

![82124010-5da0e180-9794-11ea-94c4-ddf5f2c0e190](https://user-images.githubusercontent.com/8590311/86396825-980a0380-bc9a-11ea-90b7-c0a0dab03f4a.png)

Second option, closer to existing design:

![home-with-title](https://user-images.githubusercontent.com/8590311/86397306-7f4e1d80-bc9b-11ea-8b17-404d41e99e12.jpg)
(I reduce the font-size to 1rem, all other css changes should be in the screenshot)

If we go with an approach like this I think it would make sense to show `text-decoration: underline;` on hover (for both title and entry text).

What do you think?

**Comment by cglatot** [comment]
I like both designs - but agree to the smaller font. Having more room for the actual title / chapter name would be nice - even across all the other cards too.

**Comment by hkalexling** [comment]
@jaredlt As always, love your designs! I think I will go with the second one (closer to the current design). I will work on this soon 👍

**Comment by hkalexling** [comment]
Added in [v0.7.3](https://github.com/hkalexling/Mango/releases/tag/v0.7.3). Thanks to @cglatot for the feature requests and thank you @jaredlt for your UI design!
