### ISSUE TITLE
[Feature Request] Change the colour of the read percent on dark mode

### ISSUE THREAD

**Issue by cglatot** [hkalexling/Mango#85]
**Is your feature request related to a problem? Please describe.**
A lot of the manga in my library begins with a black and white scan. When on dark mode, the percentage is also black and white and can be pretty hard to see. It's still visible, but can blend in and makes it harder to look at a glance.

**Describe the solution you'd like**
Have the percentage have a colour.

Example of the percentage being difficult to see against black and white background:

![image](https://user-images.githubusercontent.com/10439257/86412131-3e173700-bcb6-11ea-9db7-9e989c41f0dc.png)

**Comment by hkalexling** [comment]
Added in [v0.7.3](https://github.com/hkalexling/Mango/releases/tag/v0.7.3). Thanks for the request!
