### ISSUE TITLE
[Bug Report] Series suddenly disappeared from "Continue Reading"

### ISSUE THREAD

**Issue by cglatot** [hkalexling/Mango#86]
**Describe the bug**
I have been reading through Demon Slayer (Kimetsu no Yaiba) - and when I reached the latest chapter, instead of the "Next" button taking me to the next chapter, it instead took me back to the Library for Demon Slayer. When I now look at the Home page, the entry for Demon Slayer is no longer there. There are more chapters that are unread, and even a chapter currently in progress, as you can see here: 
![image](https://user-images.githubusercontent.com/10439257/86536371-d859c380-bede-11ea-90ba-15b3be28688e.png)

**To Reproduce**
I was reading using the browser reader on Chrome (latest).
Clicked the "Next" button at the bottom of the reader to go to the next chapter, but took me back to the Demon Slayer library overview.

**Expected behavior**
Demon Slayer should be showing up in the Continue Reading section.

**Environment (please complete the following information):**
 - Android, Chrome OS, Windows
 - Chrome 83.0.4103.116, Edge latest
 - Mango Version 0.7.2 and again on 0.7.3

**Comment by jaredlt** [comment]
@cglatot could you post the filenames for those 3? And are all files for the series in a single folder or do you have subfolders? I wonder if there is a naming discrepancy that's confusing things (just a guess).

**Comment by cglatot** [comment]
@jaredlt yup - seems to be a naming convention. The last chapters I read that were tracked have this naming:
![image](https://user-images.githubusercontent.com/10439257/86541639-6006f880-bf06-11ea-898d-298c8ffc3242.png)

And the next set of chapters are like this:
![image](https://user-images.githubusercontent.com/10439257/86541649-701ed800-bf06-11ea-9d77-e4b809ad3355.png)

This is a format that is likely going to be an issue for many series - as ones that have volumes out will often have the Vol number - but for issues where they have only been in Shonen Jump, but no volume released yet, will only have the Chapter numbers. It would be nice if the logic / parser could honor that, as the Chapter numbers are still progressive.

**Comment by hkalexling** [comment]
Thanks for reporting. Yes, it's indeed due to the different naming conventions. The web interface and the Mango core use different algorithms to sort the files in a folder, and in this case, the core algorithm thinks "Vol.20 Ch.178.5 Extras.cbz" is the last chapter in the folder. I agree it's a terrible design that breaks user expectations. I will try to find a way to fix it .

**Comment by hkalexling** [comment]
Fixed in [v0.8.0](https://github.com/hkalexling/Mango/releases/tag/v0.8.0). Thanks for the bug report!

**Comment by cglatot** [comment]
@hkalexling fantastic work with these updates - really loving it :)

Can confirm that this automatically picked up my next chapter again and seems to be working well so far :D
