### ISSUE TITLE
Probably not an issue

### ISSUE THREAD

**Issue by Kingfoxl** [hkalexling/Mango#88]
I cant seem to find the default username and password, and not sure what or where STDOUT is. Any pointers to where i should look?
Thanks in advance.

**Comment by zFerry98** [comment]
> I cant seem to find the default username and password, and not sure what or where STDOUT is. Any pointers to where i should look?
> Thanks in advance.

It depends on the system you used, installed on linux by downloading the "mango" file from the releases and starting it from the folder itself with "./mango" (after setting permission "sudo chmod + x ./mango", in the console of the terminal used for run these commands, the username and password appear written between the output lines.

If you used docker, simply click on the mango container and the log is opened, you are told the password and user name (if there is not, it means that you have reset the docker logs, in that case delete the container and do it again.

**Comment by Kingfoxl** [comment]
Perfect, thanks alot. :)
