### ISSUE TITLE
Switch theme based on system setting

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#91]
**Is your feature request related to a problem? Please describe.**
The theme should switch to the desired darkness based on what the current device is saying it is set to

**Describe the solution you'd like**
Implement something akin to this https://flaviocopes.com/javascript-detect-dark-mode/

**Describe a small use-case for this feature request**
I'd like to have dark mode when my phone is set to dark mode. Would be sweeeet.

**Additional context**
Dark mode is dark

**Comment by hkalexling** [comment]
Added in [v0.9.0](https://github.com/hkalexling/Mango/releases/tag/v0.9.0). Thanks for the request!
