### ISSUE TITLE
[Feature Request] Random Section 

### ISSUE THREAD

**Issue by limitlessbritt** [hkalexling/Mango#92]
Hi there, loving mango so far. It would be nice to have a "random" section on the home page. For example, underneath the "recently added" section there could a a small list of mangas/comics that have been randomly selected with their covers displayed. Cheers!

**Comment by hkalexling** [comment]
Hi, thanks for reaching out!

The home screen design was inspired by Plex, and Plex does not have a "random" section. Why do you think it's useful? Is there a specific use-case?

**Comment by limitlessbritt** [comment]
I've never used plex before so I was unaware. Its useful to me because I'm indecisive when trying to pick a new series to read next. Thats one use-case. Could be useful for people who have big libraries as well who get lost in their library. Cheers!

**Comment by jaredlt** [comment]
Plex does have this. But they call it `Start Watching`. It serves up a list of random series that you have not started yet. I could see room for a `Start Reading` section which does something similar.

**Comment by hkalexling** [comment]
The feature has been added in [v0.10.0](https://github.com/hkalexling/Mango/releases/tag/v0.10.0). Thanks for the request!
