### ISSUE TITLE
[Feature Request] Thumbnail Generation

### ISSUE THREAD

**Issue by WiseMMO** [hkalexling/Mango#93]
Hello,

I'm just testing Mango out to move away from Komga, I have everything set-up on a server with an i7 (8000+ bench score, I don't remember the exact generation) and 32GB of RAM.

The web interface is accessed from a simple NGINX reverse proxy in a subdomain virtual host. Everything works properly except browsing the web interface which is extremely slow (Both on Chrome and Firefox). 

I have a bunch of very high resolution digital manga (in cbz) (3000h and up in resolution) and sometimes the page stays white for 3-4 seconds to load newer volumes while browsing any specific manga page. 

I'm assuming this is because Mango lets my client downscale the pictures instead of preemptively preparing them itself? Is there any way I can mitigate this? 

I should also mention that this is remote and not on local network

**Comment by hkalexling** [comment]
Hi, thanks for reaching out!

> I'm assuming this is because Mango lets my client downscale the pictures instead of preemptively preparing them itself?

Yes, this might be the reason but I am not sure. The web interface lazy loads images, which means it only load and display images when they enter the viewport, so your browser only needs to downscale the visible images.

Could you please find a typical cbz in your collection, and check the file size and resolution of the first page? And how many cbz files do you usually have in a manga folder? I will test and see if I can reproduce the issue.

**Comment by WiseMMO** [comment]
> Hi, thanks for reaching out!
> 
> > I'm assuming this is because Mango lets my client downscale the pictures instead of preemptively preparing them itself?
> 
> Yes, this might be the reason but I am not sure. The web interface lazy loads images, which means it only loads and displays images when they enter the viewport, so your browser only needs to downscale the visible images.
> 
> Could you please find a typical cbz in your collection, and check the file size and resolution of the first page? And how many cbz files do you usually have in a manga folder? I will test and see if I can reproduce the issue.

The worst example I have is a folder containing 40 volumes of a digital version of Berserk.

Each file is ranges in size from 800MB (the biggest one) and 200MB (the smallest one), the median is around 450MB per file. They contain about 250 pages per volume, and their cover is 1810x2560 in resolution.

Another exampe is BLAME! containing only 6 volumes, but being AS slow if not more and the resolution of each cover is 2142x3056, these volumes go from 700MB to 1.2GB and they have about 400 pages each.

**Comment by hkalexling** [comment]
From the GIF I saw two issues:

1. The cards are initially blank and the images take some time to load
2. Sometimes when scrolling, the whole page turns white, and it returns to normal after a few seconds

The first issue is completely normal. As you correctly noted, currently Mango does not generate thumbnails when scanning the library, so high-resolution covers take some time to load. Due to the same reason, in OPDS the covers take longer to download. We do need the thumbnail generation feature before v1.0, but I don't think it's important at this stage.

The second issue is weird and I couldn't reproduce it. I've created a folder containing 1000 cbz files, where each file has a 4928 × 3280 cover image. On my i7 MacBook Pro with 32GB of RAM, both Firefox and Chrome scroll smoothly. I will test it with less powerful devices tomorrow.

**Comment by WiseMMO** [comment]
> From the GIF I saw two issues:
> 
> 1. The cards are initially blank and the images take some time to load
> 2. Sometimes when scrolling, the whole page turns white, and it returns to normal after a few seconds
> 
> The first issue is completely normal. As you correctly noted, currently Mango does not generate thumbnails when scanning the library, so high-resolution covers take some time to load. Due to the same reason, in OPDS the covers take longer to download. We do need the thumbnail generation feature before v1.0, but I don't think it's important at this stage.
> 
> The second issue is weird and I couldn't reproduce it. I've created a folder containing 1000 cbz files, where each file has a 4928 × 3280 cover image. On my i7 MacBook Pro with 32GB of RAM, both Firefox and Chrome scroll smoothly. I will test it with less powerful devices tomorrow.

I can confirm that the second issue is my work laptop being a piece of garbage. Admittedly I did not try scrolling on my less powerful devices, on my iPad it scrolls smoothly.

The slower cover imagine loading is a bit annoying, it lags my brain but it's ok to wait for, will keep using the app and see how it is. Most needed feature right now for me would be multi mark read and unread, had to go through 25 volumes of Berserk to mark as read!

**Comment by hkalexling** [comment]
Great! The batch marking feature has been requested in #75 and you can subscribe to that issue to get updated. I should be able to work on it soon, after finishing #48.

**Comment by WiseMMO** [comment]
> Great! The batch marking feature has been requested in #75 and you can subscribe to that issue to get updated. I should be able to work on it soon, after finishing #48.

#48 is awesome. Just a generic question that I don't know if I should open an enhancement request yet. Would it be possible to do something like YACServer?

YACServer headless could be run from a docker image like  [https://hub.docker.com/r/muallin/yacreaderlibrary-server-docker/](this) one and I would stream files directly from the server to their iOS app YacReader. Obviously there's no native app for Mango, but my idea is generally avoiding using browsers as much as possible so to have native library view within one app and native page scrolling while reading and also downloading as much, like you can do with OPDS, because that would defeat the purpose of having a server!

**Comment by hkalexling** [comment]
I am not sure I understand. Are you requesting for headless mode or native apps?

For Android, we have #33. I hate Java and Kotlin with a passion so I really don't want to work on that :) Hopefully someone will help, and if not I can push myself to do it before v1.0. As for iOS, I am an iOS developer myself, so I can develop and publish a native app when I have the time. Feel free to open a feature request if you want.

**Comment by WiseMMO** [comment]
> I am not sure I understand. Are you requesting for headless mode or native apps?
> 
> For Android, we have #33. I hate Java and Kotlin with a passion so I really don't want to work on that :) Hopefully someone will help, and if not I can push myself to do it before v1.0. As for iOS, I am an iOS developer myself, so I can develop and publish a native app when I have the time. Feel free to open a feature request if you want.

Technically YACServer does not support a headless server, it is usually used under Windows with a GUI and then the client connects to the server via the native app. What I was asking for was something kinda like the YACReader app for iOS, where it just connects to your library server and STREAMS pages to your client, without downloading them or going through a browser!

**Comment by hkalexling** [comment]
@WiseMMO Just to let you know, the batch marking feature has been added in [v0.10.0](https://github.com/hkalexling/Mango/releases/tag/v0.10.0).

**Comment by hkalexling** [comment]
In [v0.15.0](https://github.com/hkalexling/Mango/releases/tag/v0.15.0) Mango generates thumbnails as a background task. Thanks for the feature request!
