### ISSUE TITLE
[Feature Request] Respect the `*_PROXY` environment variables

### ISSUE THREAD

**Issue by CaligulaCa3sar** [hkalexling/Mango#94]
**Describe the bug**
Unsure if a bug or not, but I have Mango deployed as a Docker container.  I need it to use a local proxy server address for accessing Mangadex.  The proxy address and port has been set in the HTTP_PROXY and HTTPS_PROXY environment variables (confirmed by issuing the env command in a shell) but Mango appears to ignore this and tries to access the site directly.

**To Reproduce**
1. Set HTTP_PROXY and HTTPS_PROXY environment variables in the Docker container.
2. Search Mangadex for a title on the Mango "Download" page.
3. Mango tries to access Mangadex directly.

**Expected behavior**
Mango should be trying to send traffic via the local proxy.

**Environment (please complete the following information):**
 - OS: Synology DSM
 - Pale Moon
 - v0.10.0

**Docker (if you are running Mango in a Docker container)**
- / # env
HTTPS_PROXY=https://(IP of Proxy):3128
HOSTNAME=Mango
SHLVL=1                                                                         
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
HTTP_PROXY=http://(IP of Proxy):3128

**Comment by hkalexling** [comment]
You are right - currently Mango doesn't respect the `*_PROXY` environment variables. I am turning this into a feature request. It's a small feature, so it will probably be added in the next release.

**Comment by CaligulaCa3sar** [comment]
That's great!  I look forward to the release.
Apologies for classifying this incorrectly.

**Comment by hkalexling** [comment]
The feature has been added in [v0.11.0](https://github.com/hkalexling/Mango/releases/tag/v0.11.0). Sorry for the long delay, and thank you for the request!

**Comment by CaligulaCa3sar** [comment]
Works like a charm!  Thank you.
