### ISSUE TITLE
[Bug Report]  Could not bind to '0.0.0.0:9000'

### ISSUE THREAD

**Issue by NodokaMurmevent** [hkalexling/Mango#96]
**Describe the bug**
i download the last binary 0.10.0 and i try to lunch for the fist time the app

**To Reproduce**
1. Go to the install folder
2. make mango executable
3. write ./mango on shell
4. error : 
```
The config file /home/nodoka/.config/mango/config.yml does not exist. Do you want mango to dump the default config there? [Y/n]
Y
The config file has been created at /home/nodoka/.config/mango/config.yml.
[INFO]    2020/08/14 19:03:05 | The queue DB directory /home/nodoka/mango does not exist. Attepmting to create it
[NONE]    2020/08/14 19:03:05 | Initial user created. You can log in with {"username" => "admin", "password" => "blup"}
Unhandled exception: Could not bind to '0.0.0.0:9000': Address in use (Socket::BindError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
and the process finish

**Expected behavior**

expected to see mango server start

**Environment (please complete the following information):**
 - OS: Manjaro rolling Realease
 - Mango Version v0.10.0

**Additional context**
also tried in root user. same problem

**Comment by hkalexling** [comment]
The error message says that the default port 9000 is already being used. Please edit the config file at `/home/nodoka/.config/mango/config.yml` to change the port number.
