### ISSUE TITLE
[Bug Report] Username with a `-` cannot be added

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#99]
**Describe the bug**
I think it is kinda essential today to support mroe characters than just alphanum + `_`. Special characters exist too :p

**To Reproduce**
- Try create a user on the CLI with special characters in the password. It will break.

**Expected behavior**
- User account with 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Mango Version: 0.11

**Docker (if you are running Mango in a Docker container)**
- Native

**Additional context**

```
Unhandled exception: Username should contain alphanumeric characters and underscores only (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```

**Comment by hkalexling** [comment]
I can't reproduce this. I ran

```
./mango admin user add -u alex -p 'slldfj+-2342;/`~"'
```

and worked correctly without breaking. The error message seems to indicate that the username contains illegle characters. Could you paste the command you use so I can check?

**Comment by flying-sausages** [comment]
Oooops, my bad! I read it incorrectly. I'm adding users that exist on the unix system, and some contain hyphens aka minus symbols. I suspect that's what it would be.

**Comment by hkalexling** [comment]
The username validation rule has been updated in [v0.12.0](https://github.com/hkalexling/Mango/releases/tag/v0.12.0) to allow hyphens. You can find the full Regex here https://github.com/hkalexling/Mango/blob/a612cc15fb8c4a505cde805ea89aa88084b28897/src/util/validation.cr#L5

Thanks for the report!
